
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 30 00:45:08 VET 2011
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Oct 30 00:45:08 VET 2011
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\122\000\002\002\005\000\002\002\004\000\002\002" +
    "\006\000\002\002\006\000\002\002\007\000\002\002\007" +
    "\000\002\002\010\000\002\002\010\000\002\002\011\000" +
    "\002\002\003\000\002\002\004\000\002\002\005\000\002" +
    "\002\005\000\002\002\006\000\002\002\006\000\002\002" +
    "\007\000\002\003\005\000\002\003\003\000\002\004\005" +
    "\000\002\004\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\005\003\000\002\005\003\000\002\005" +
    "\003\000\002\006\004\000\002\007\003\000\002\007\003" +
    "\000\002\007\003\000\002\010\005\000\002\010\010\000" +
    "\002\010\006\000\002\010\003\000\002\011\005\000\002" +
    "\012\004\000\002\013\005\000\002\013\003\000\002\014" +
    "\004\000\002\014\006\000\002\015\011\000\002\015\015" +
    "\000\002\016\015\000\002\016\017\000\002\017\010\000" +
    "\002\020\010\000\002\021\012\000\002\021\013\000\002" +
    "\023\006\000\002\023\004\000\002\022\006\000\002\022" +
    "\005\000\002\024\005\000\002\024\003\000\002\025\003" +
    "\000\002\025\003\000\002\026\006\000\002\026\005\000" +
    "\002\027\003\000\002\027\003\000\002\027\003\000\002" +
    "\027\003\000\002\027\003\000\002\027\003\000\002\030" +
    "\005\000\002\030\003\000\002\031\003\000\002\031\003" +
    "\000\002\032\005\000\002\032\003\000\002\033\003\000" +
    "\002\033\003\000\002\033\003\000\002\033\003\000\002" +
    "\034\005\000\002\034\003\000\002\034\003\000\002\034" +
    "\003\000\002\034\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\246\000\032\005\005\015\007\016\011\020\025\021" +
    "\015\030\006\032\020\033\032\037\031\040\023\041\021" +
    "\053\017\001\002\000\004\053\uffec\001\002\000\006\021" +
    "\245\062\246\001\002\000\016\017\045\021\037\022\042" +
    "\044\114\061\043\062\046\001\002\000\006\002\ufff8\053" +
    "\235\001\002\000\004\053\uffe6\001\002\000\016\017\045" +
    "\021\037\022\042\044\114\061\043\062\046\001\002\000" +
    "\004\053\uffe5\001\002\000\004\053\215\001\002\000\004" +
    "\021\200\001\002\000\006\017\175\025\176\001\002\000" +
    "\004\002\174\001\002\000\030\005\005\015\135\016\011" +
    "\020\025\021\015\030\006\032\020\033\032\037\031\040" +
    "\023\041\021\001\002\000\004\053\106\001\002\000\004" +
    "\021\uffe1\001\002\000\004\053\uffee\001\002\000\004\021" +
    "\uffe2\001\002\000\004\053\uffeb\001\002\000\014\017\045" +
    "\021\037\022\042\061\043\062\046\001\002\000\004\053" +
    "\uffe9\001\002\000\004\053\uffed\001\002\000\004\053\uffe7" +
    "\001\002\000\004\021\uffe3\001\002\000\004\021\035\001" +
    "\002\000\004\053\uffe8\001\002\000\004\053\uffea\001\002" +
    "\000\004\025\036\001\002\000\014\017\045\021\037\022" +
    "\042\061\043\062\046\001\002\000\052\004\uffb1\006\uffb1" +
    "\007\uffb1\011\uffb1\012\uffb1\013\uffb1\014\uffb1\023\uffb1\026" +
    "\uffb1\034\uffb1\035\uffb1\042\uffb1\043\uffb1\045\uffb1\046\uffb1" +
    "\047\uffb1\050\uffb1\053\uffb1\054\uffb1\055\uffb1\001\002\000" +
    "\010\011\051\023\053\034\063\001\002\000\052\004\uffb9" +
    "\006\uffb9\007\uffb9\011\uffb9\012\uffb9\013\uffb9\014\uffb9\023" +
    "\uffb9\026\uffb9\034\uffb9\035\uffb9\042\uffb9\043\uffb9\045\uffb9" +
    "\046\uffb9\047\uffb9\050\uffb9\053\uffb9\054\uffb9\055\uffb9\001" +
    "\002\000\052\004\uffb3\006\uffb3\007\uffb3\011\uffb3\012\uffb3" +
    "\013\uffb3\014\uffb3\023\uffb3\026\uffb3\034\uffb3\035\uffb3\042" +
    "\uffb3\043\uffb3\045\uffb3\046\uffb3\047\uffb3\050\uffb3\053\uffb3" +
    "\054\uffb3\055\uffb3\001\002\000\052\004\uffb2\006\uffb2\007" +
    "\uffb2\011\uffb2\012\uffb2\013\uffb2\014\uffb2\023\uffb2\026\uffb2" +
    "\034\uffb2\035\uffb2\042\uffb2\043\uffb2\045\uffb2\046\uffb2\047" +
    "\uffb2\050\uffb2\053\uffb2\054\uffb2\055\uffb2\001\002\000\052" +
    "\004\060\006\057\007\uffbd\011\uffbd\012\uffbd\013\uffbd\014" +
    "\uffbd\023\uffbd\026\uffbd\034\uffbd\035\uffbd\042\uffbd\043\uffbd" +
    "\045\uffbd\046\uffbd\047\uffbd\050\061\053\uffbd\054\uffbd\055" +
    "\056\001\002\000\014\017\045\021\037\022\042\061\043" +
    "\062\046\001\002\000\052\004\uffb0\006\uffb0\007\uffb0\011" +
    "\uffb0\012\uffb0\013\uffb0\014\uffb0\023\uffb0\026\uffb0\034\uffb0" +
    "\035\uffb0\042\uffb0\043\uffb0\045\uffb0\046\uffb0\047\uffb0\050" +
    "\uffb0\053\uffb0\054\uffb0\055\uffb0\001\002\000\010\011\051" +
    "\012\050\023\053\001\002\000\052\004\uffb4\006\uffb4\007" +
    "\uffb4\011\uffb4\012\uffb4\013\uffb4\014\uffb4\023\uffb4\026\uffb4" +
    "\034\uffb4\035\uffb4\042\uffb4\043\uffb4\045\uffb4\046\uffb4\047" +
    "\uffb4\050\uffb4\053\uffb4\054\uffb4\055\uffb4\001\002\000\014" +
    "\017\uffbc\021\uffbc\022\uffbc\061\uffbc\062\uffbc\001\002\000" +
    "\014\017\045\021\037\022\042\061\043\062\046\001\002" +
    "\000\014\017\uffbb\021\uffbb\022\uffbb\061\uffbb\062\uffbb\001" +
    "\002\000\052\004\060\006\057\007\uffbe\011\uffbe\012\uffbe" +
    "\013\uffbe\014\uffbe\023\uffbe\026\uffbe\034\uffbe\035\uffbe\042" +
    "\uffbe\043\uffbe\045\uffbe\046\uffbe\047\uffbe\050\061\053\uffbe" +
    "\054\uffbe\055\056\001\002\000\014\017\045\021\037\022" +
    "\042\061\043\062\046\001\002\000\014\017\uffb6\021\uffb6" +
    "\022\uffb6\061\uffb6\062\uffb6\001\002\000\014\017\uffb7\021" +
    "\uffb7\022\uffb7\061\uffb7\062\uffb7\001\002\000\014\017\uffb8" +
    "\021\uffb8\022\uffb8\061\uffb8\062\uffb8\001\002\000\014\017" +
    "\uffb5\021\uffb5\022\uffb5\061\uffb5\062\uffb5\001\002\000\052" +
    "\004\uffba\006\uffba\007\uffba\011\uffba\012\uffba\013\uffba\014" +
    "\uffba\023\uffba\026\uffba\034\uffba\035\uffba\042\uffba\043\uffba" +
    "\045\uffba\046\uffba\047\uffba\050\uffba\053\uffba\054\uffba\055" +
    "\uffba\001\002\000\014\017\045\021\037\022\042\061\043" +
    "\062\046\001\002\000\012\011\051\023\053\035\065\053" +
    "\066\001\002\000\014\017\045\021\037\022\042\061\043" +
    "\062\046\001\002\000\026\005\005\016\011\020\025\021" +
    "\015\030\006\032\020\033\032\037\031\040\023\041\021" +
    "\001\002\000\004\053\070\001\002\000\030\005\005\016" +
    "\011\020\025\021\015\030\006\032\020\033\032\036\072" +
    "\037\031\040\023\041\021\001\002\000\004\053\uffef\001" +
    "\002\000\004\021\073\001\002\000\004\053\uffd4\001\002" +
    "\000\010\011\051\023\053\053\075\001\002\000\026\005" +
    "\005\016\011\020\025\021\015\030\006\032\020\033\032" +
    "\037\031\040\023\041\021\001\002\000\004\053\077\001" +
    "\002\000\030\005\005\016\011\020\025\021\015\030\006" +
    "\032\020\033\032\036\100\037\031\040\023\041\021\001" +
    "\002\000\004\021\101\001\002\000\004\053\uffd3\001\002" +
    "\000\006\014\104\053\uffdb\001\002\000\012\011\051\014" +
    "\uffd9\023\053\053\uffd9\001\002\000\014\017\045\021\037" +
    "\022\042\061\043\062\046\001\002\000\012\011\051\014" +
    "\uffda\023\053\053\uffda\001\002\000\026\005\005\016\011" +
    "\020\025\021\015\030\006\032\020\033\032\037\031\040" +
    "\023\041\021\001\002\000\004\053\110\001\002\000\030" +
    "\005\005\016\011\020\025\021\015\024\111\030\006\032" +
    "\020\033\032\037\031\040\023\041\021\001\002\000\016" +
    "\017\045\021\037\022\042\044\114\061\043\062\046\001" +
    "\002\000\022\007\123\011\051\023\053\026\121\045\125" +
    "\046\124\047\117\054\122\001\002\000\010\042\130\043" +
    "\131\053\uffd2\001\002\000\014\017\045\021\037\022\042" +
    "\061\043\062\046\001\002\000\012\013\uffc9\042\uffc9\043" +
    "\uffc9\053\uffc9\001\002\000\022\007\123\011\051\023\053" +
    "\026\121\045\125\046\124\047\117\054\122\001\002\000" +
    "\014\017\uffbf\021\uffbf\022\uffbf\061\uffbf\062\uffbf\001\002" +
    "\000\014\017\045\021\037\022\042\061\043\062\046\001" +
    "\002\000\014\017\uffc4\021\uffc4\022\uffc4\061\uffc4\062\uffc4" +
    "\001\002\000\014\017\uffc3\021\uffc3\022\uffc3\061\uffc3\062" +
    "\uffc3\001\002\000\014\017\uffc2\021\uffc2\022\uffc2\061\uffc2" +
    "\062\uffc2\001\002\000\014\017\uffc0\021\uffc0\022\uffc0\061" +
    "\uffc0\062\uffc0\001\002\000\014\017\uffc1\021\uffc1\022\uffc1" +
    "\061\uffc1\062\uffc1\001\002\000\016\011\051\013\uffc6\023" +
    "\053\042\uffc6\043\uffc6\053\uffc6\001\002\000\016\017\045" +
    "\021\037\022\042\044\114\061\043\062\046\001\002\000" +
    "\016\017\uffc8\021\uffc8\022\uffc8\044\uffc8\061\uffc8\062\uffc8" +
    "\001\002\000\016\017\uffc7\021\uffc7\022\uffc7\044\uffc7\061" +
    "\uffc7\062\uffc7\001\002\000\012\013\uffca\042\uffca\043\uffca" +
    "\053\uffca\001\002\000\014\017\045\021\037\022\042\061" +
    "\043\062\046\001\002\000\016\011\051\013\uffc5\023\053" +
    "\042\uffc5\043\uffc5\053\uffc5\001\002\000\004\053\171\001" +
    "\002\000\004\053\137\001\002\000\030\005\005\015\140" +
    "\016\011\020\025\021\015\030\006\032\020\033\032\037" +
    "\031\040\023\041\021\001\002\000\006\002\ufffe\053\141" +
    "\001\002\000\006\002\ufffd\056\143\001\002\000\006\002" +
    "\ufffa\053\167\001\002\000\004\021\145\001\002\000\006" +
    "\002\ufff0\053\ufff0\001\002\000\004\017\146\001\002\000" +
    "\012\012\147\037\031\040\023\041\021\001\002\000\004" +
    "\053\163\001\002\000\004\021\162\001\002\000\006\012" +
    "\153\060\152\001\002\000\010\037\031\040\023\041\021" +
    "\001\002\000\004\053\154\001\002\000\026\005\005\016" +
    "\011\020\025\021\015\030\006\032\020\033\032\037\031" +
    "\040\023\041\021\001\002\000\004\053\156\001\002\000" +
    "\030\005\005\016\011\020\025\021\015\030\006\032\020" +
    "\033\032\037\031\040\023\041\021\057\157\001\002\000" +
    "\006\002\uffcf\053\uffcf\001\002\000\004\021\161\001\002" +
    "\000\006\012\uffce\060\uffce\001\002\000\006\012\uffcd\060" +
    "\uffcd\001\002\000\026\005\005\016\011\020\025\021\015" +
    "\030\006\032\020\033\032\037\031\040\023\041\021\001" +
    "\002\000\004\053\165\001\002\000\030\005\005\016\011" +
    "\020\025\021\015\030\006\032\020\033\032\037\031\040" +
    "\023\041\021\057\166\001\002\000\006\002\uffd0\053\uffd0" +
    "\001\002\000\006\002\ufff9\056\143\001\002\000\006\002" +
    "\ufff1\053\ufff1\001\002\000\006\002\ufff6\056\143\001\002" +
    "\000\006\002\ufff3\053\173\001\002\000\006\002\ufff2\056" +
    "\143\001\002\000\004\002\000\001\002\000\006\012\201" +
    "\021\200\001\002\000\014\017\045\021\037\022\042\061" +
    "\043\062\046\001\002\000\010\011\051\023\053\053\uffdc" +
    "\001\002\000\012\012\uffdd\051\211\053\uffdd\060\uffdd\001" +
    "\002\000\004\053\uffcb\001\002\000\006\012\204\060\203" +
    "\001\002\000\004\021\205\001\002\000\004\053\uffcc\001" +
    "\002\000\012\012\uffe0\051\206\053\uffe0\060\uffe0\001\002" +
    "\000\004\022\207\001\002\000\004\052\210\001\002\000" +
    "\010\012\uffdf\053\uffdf\060\uffdf\001\002\000\004\022\212" +
    "\001\002\000\004\052\213\001\002\000\010\012\uffde\053" +
    "\uffde\060\uffde\001\002\000\006\053\uffe4\060\203\001\002" +
    "\000\030\005\005\015\216\016\011\020\025\021\015\030" +
    "\006\032\020\033\032\037\031\040\023\041\021\001\002" +
    "\000\006\002\001\053\217\001\002\000\006\002\uffff\056" +
    "\143\001\002\000\006\002\ufffc\053\221\001\002\000\006" +
    "\002\ufffb\056\143\001\002\000\010\013\223\042\130\043" +
    "\131\001\002\000\004\053\224\001\002\000\026\005\005" +
    "\016\011\020\025\021\015\030\006\032\020\033\032\037" +
    "\031\040\023\041\021\001\002\000\004\053\226\001\002" +
    "\000\032\005\005\010\227\016\011\020\025\021\015\027" +
    "\230\030\006\032\020\033\032\037\031\040\023\041\021" +
    "\001\002\000\004\053\231\001\002\000\004\053\uffd6\001" +
    "\002\000\026\005\005\016\011\020\025\021\015\030\006" +
    "\032\020\033\032\037\031\040\023\041\021\001\002\000" +
    "\004\053\233\001\002\000\030\005\005\016\011\020\025" +
    "\021\015\027\234\030\006\032\020\033\032\037\031\040" +
    "\023\041\021\001\002\000\004\053\uffd5\001\002\000\006" +
    "\002\ufff7\056\143\001\002\000\006\002\ufff5\053\237\001" +
    "\002\000\006\002\ufff4\056\143\001\002\000\010\042\130" +
    "\043\131\053\241\001\002\000\026\005\005\016\011\020" +
    "\025\021\015\030\006\032\020\033\032\037\031\040\023" +
    "\041\021\001\002\000\004\053\243\001\002\000\030\005" +
    "\005\016\011\020\025\021\015\030\006\031\244\032\020" +
    "\033\032\037\031\040\023\041\021\001\002\000\004\053" +
    "\uffd1\001\002\000\004\053\uffd8\001\002\000\004\060\247" +
    "\001\002\000\004\021\250\001\002\000\004\053\uffd7\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\246\000\034\002\015\004\012\005\021\006\026\007" +
    "\013\011\003\012\023\014\033\015\025\016\032\017\027" +
    "\020\007\022\011\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\024\237\026\114\030\111\032\043\034\040" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\024" +
    "\221\026\114\030\111\032\043\034\040\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\213\001\001\000" +
    "\002\001\001\000\002\001\001\000\032\004\135\005\021" +
    "\006\026\007\013\011\003\012\023\014\033\015\025\016" +
    "\032\017\027\020\007\022\011\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\013\101\030\102\032\043\034\040" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\030\037\032" +
    "\043\034\040\001\001\000\002\001\001\000\004\031\051" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\033\054\001\001\000\010\030\046\032\043" +
    "\034\040\001\001\000\002\001\001\000\004\031\051\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\032\053" +
    "\034\040\001\001\000\002\001\001\000\004\033\054\001" +
    "\001\000\004\034\061\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\030\063\032\043\034\040\001\001\000\004" +
    "\031\051\001\001\000\010\030\073\032\043\034\040\001" +
    "\001\000\032\004\066\005\021\006\026\007\013\011\003" +
    "\012\023\014\033\015\025\016\032\017\027\020\007\022" +
    "\011\001\001\000\002\001\001\000\030\005\070\006\026" +
    "\007\013\011\003\012\023\014\033\015\025\016\032\017" +
    "\027\020\007\022\011\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\031\051\001\001\000" +
    "\032\004\075\005\021\006\026\007\013\011\003\012\023" +
    "\014\033\015\025\016\032\017\027\020\007\022\011\001" +
    "\001\000\002\001\001\000\030\005\070\006\026\007\013" +
    "\011\003\012\023\014\033\015\025\016\032\017\027\020" +
    "\007\022\011\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\031\051\001\001\000\010\030" +
    "\104\032\043\034\040\001\001\000\004\031\051\001\001" +
    "\000\032\004\106\005\021\006\026\007\013\011\003\012" +
    "\023\014\033\015\025\016\032\017\027\020\007\022\011" +
    "\001\001\000\002\001\001\000\030\005\070\006\026\007" +
    "\013\011\003\012\023\014\033\015\025\016\032\017\027" +
    "\020\007\022\011\001\001\000\014\024\112\026\114\030" +
    "\111\032\043\034\040\001\001\000\006\027\132\031\051" +
    "\001\001\000\004\025\126\001\001\000\010\030\115\032" +
    "\043\034\040\001\001\000\002\001\001\000\006\027\117" +
    "\031\051\001\001\000\002\001\001\000\010\030\125\032" +
    "\043\034\040\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\031\051\001\001\000\012\026\131\030\111\032\043" +
    "\034\040\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\030\133\032\043\034\040\001\001" +
    "\000\004\031\051\001\001\000\002\001\001\000\002\001" +
    "\001\000\030\005\070\006\026\007\013\011\003\012\023" +
    "\014\033\015\025\016\032\017\027\020\007\022\011\001" +
    "\001\000\002\001\001\000\006\003\141\021\143\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\007\147\023\150\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\007" +
    "\157\001\001\000\002\001\001\000\032\004\154\005\021" +
    "\006\026\007\013\011\003\012\023\014\033\015\025\016" +
    "\032\017\027\020\007\022\011\001\001\000\002\001\001" +
    "\000\030\005\070\006\026\007\013\011\003\012\023\014" +
    "\033\015\025\016\032\017\027\020\007\022\011\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\032\004\163\005\021\006\026\007\013" +
    "\011\003\012\023\014\033\015\025\016\032\017\027\020" +
    "\007\022\011\001\001\000\002\001\001\000\030\005\070" +
    "\006\026\007\013\011\003\012\023\014\033\015\025\016" +
    "\032\017\027\020\007\022\011\001\001\000\002\001\001" +
    "\000\004\021\167\001\001\000\002\001\001\000\006\003" +
    "\171\021\143\001\001\000\002\001\001\000\004\021\167" +
    "\001\001\000\002\001\001\000\004\010\201\001\001\000" +
    "\010\030\176\032\043\034\040\001\001\000\004\031\051" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\030\005\070\006\026\007\013\011\003\012" +
    "\023\014\033\015\025\016\032\017\027\020\007\022\011" +
    "\001\001\000\002\001\001\000\006\003\217\021\143\001" +
    "\001\000\002\001\001\000\004\021\167\001\001\000\004" +
    "\025\126\001\001\000\002\001\001\000\032\004\224\005" +
    "\021\006\026\007\013\011\003\012\023\014\033\015\025" +
    "\016\032\017\027\020\007\022\011\001\001\000\002\001" +
    "\001\000\030\005\070\006\026\007\013\011\003\012\023" +
    "\014\033\015\025\016\032\017\027\020\007\022\011\001" +
    "\001\000\002\001\001\000\002\001\001\000\032\004\231" +
    "\005\021\006\026\007\013\011\003\012\023\014\033\015" +
    "\025\016\032\017\027\020\007\022\011\001\001\000\002" +
    "\001\001\000\030\005\070\006\026\007\013\011\003\012" +
    "\023\014\033\015\025\016\032\017\027\020\007\022\011" +
    "\001\001\000\002\001\001\000\006\003\235\021\143\001" +
    "\001\000\002\001\001\000\004\021\167\001\001\000\004" +
    "\025\126\001\001\000\032\004\241\005\021\006\026\007" +
    "\013\011\003\012\023\014\033\015\025\016\032\017\027" +
    "\020\007\022\011\001\001\000\002\001\001\000\030\005" +
    "\070\006\026\007\013\011\003\012\023\014\033\015\025" +
    "\016\032\017\027\020\007\022\011\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




  public static void main(String args[]) throws Exception{
    parser sintactico;
	
	if(args.length>0){
		sintactico = new parser(new Scanner(new FileInputStream(args[0])));
		sintactico.parse();
	}else{
		System.out.println("No se encontró el código fuente (Parámetro incorrecto)");
	}
    
  }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // factor ::= CADENA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // factor ::= ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // factor ::= NUM_FLOTANTE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // factor ::= NUM_ENTERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // factor ::= LPAREN expresion_simple RPAREN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // op_mult ::= CIRCUMFLEX 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // op_mult ::= MODULE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // op_mult ::= SLASH 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // op_mult ::= ASTERISK 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // term ::= factor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // term ::= term op_mult factor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // op_suma ::= MINUS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_suma",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // op_suma ::= PLUS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_suma",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expresion_simple ::= term 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_simple",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expresion_simple ::= expresion_simple op_suma term 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_simple",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // op_comparacion ::= GREATER_THAN_EQ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // op_comparacion ::= GREATER_THAN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // op_comparacion ::= LESS_THAN_EQ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // op_comparacion ::= LESS_THAN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // op_comparacion ::= DIFFERENT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // op_comparacion ::= EQUAL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresion_comparacion ::= expresion_simple op_comparacion expresion_simple 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_comparacion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresion_comparacion ::= NOT expresion_simple op_comparacion expresion_simple 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_comparacion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // op_logico ::= OR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_logico",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // op_logico ::= AND 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_logico",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expresion_compuesta ::= expresion_comparacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_compuesta",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresion_compuesta ::= expresion_compuesta op_logico expresion_comparacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_compuesta",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // call_proc ::= ID LPAREN RPAREN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("call_proc",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // call_proc ::= ID LPAREN list_var RPAREN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("call_proc",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // list_param ::= tipo_dato ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // list_param ::= list_param COMMA tipo_dato ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // def_proc ::= PROCEDURE ID LPAREN list_param RPAREN NEW_LINE secuencia_sent NEW_LINE ENDPROCEDURE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("def_proc",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // def_proc ::= PROCEDURE ID LPAREN RPAREN NEW_LINE secuencia_sent NEW_LINE ENDPROCEDURE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("def_proc",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // sent_while ::= WHILE expresion_compuesta NEW_LINE secuencia_sent NEW_LINE ENDWHILE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_while",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // sent_do ::= DO NEW_LINE secuencia_sent NEW_LINE LOOP_UNTIL expresion_compuesta 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_do",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // sent_for ::= FOR ID ASSIGN expresion_simple TO expresion_simple STEP expresion_simple NEW_LINE secuencia_sent NEW_LINE NEXT ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_for",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-12)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // sent_for ::= FOR ID ASSIGN expresion_simple TO expresion_simple NEW_LINE secuencia_sent NEW_LINE NEXT ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_for",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // sent_if ::= IF expresion_compuesta THEN NEW_LINE secuencia_sent NEW_LINE ELSE NEW_LINE secuencia_sent NEW_LINE ENDIF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_if",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // sent_if ::= IF expresion_compuesta THEN NEW_LINE secuencia_sent NEW_LINE ENDIF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_if",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // sent_leer ::= INPUT CADENA COMMA ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_leer",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // sent_leer ::= INPUT ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_leer",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // list_impresion ::= expresion_simple 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_impresion",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // list_impresion ::= list_impresion CONCAT expresion_simple 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_impresion",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // sent_escribir ::= PRINT list_impresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_escribir",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // sent_asignacion ::= ID ASSIGN expresion_simple 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_asignacion",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // list_var ::= ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_var",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // list_var ::= ID LPOPPER NUM_ENTERO RPOPPER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_var",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // list_var ::= list_var COMMA ID LPOPPER NUM_ENTERO RPOPPER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_var",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // list_var ::= list_var COMMA ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_var",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // tipo_dato ::= STRING 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // tipo_dato ::= FLOAT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // tipo_dato ::= INTEGER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sent_declaracion ::= tipo_dato list_var 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_declaracion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sentencia ::= call_proc 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // sentencia ::= sent_while 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // sentencia ::= sent_do 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // sentencia ::= sent_for 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // sentencia ::= sent_if 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // sentencia ::= sent_leer 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // sentencia ::= sent_escribir 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // sentencia ::= sent_asignacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // sentencia ::= sent_declaracion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // secuencia_sent ::= sentencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("secuencia_sent",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // secuencia_sent ::= secuencia_sent NEW_LINE sentencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("secuencia_sent",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sub_programa ::= def_proc 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sub_programa",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // sub_programa ::= sub_programa NEW_LINE def_proc 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sub_programa",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // programa ::= NEW_LINE END NEW_LINE sub_programa NEW_LINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // programa ::= NEW_LINE END NEW_LINE sub_programa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // programa ::= END NEW_LINE sub_programa NEW_LINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // programa ::= END NEW_LINE sub_programa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // programa ::= NEW_LINE END NEW_LINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // programa ::= END NEW_LINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // programa ::= END 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // programa ::= NEW_LINE secuencia_sent NEW_LINE END NEW_LINE sub_programa NEW_LINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // programa ::= NEW_LINE secuencia_sent NEW_LINE END NEW_LINE sub_programa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // programa ::= secuencia_sent NEW_LINE END NEW_LINE sub_programa NEW_LINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // programa ::= secuencia_sent NEW_LINE END NEW_LINE sub_programa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // programa ::= NEW_LINE secuencia_sent NEW_LINE END NEW_LINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // programa ::= NEW_LINE secuencia_sent NEW_LINE END 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= secuencia_sent NEW_LINE END NEW_LINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // programa ::= secuencia_sent NEW_LINE END 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

