
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 29 16:22:10 VET 2011
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat Oct 29 16:22:10 VET 2011
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\102\000\002\002\005\000\002\002\004\000\002\002" +
    "\006\000\002\002\006\000\002\002\007\000\002\002\004" +
    "\000\002\002\005\000\002\002\003\000\002\002\004\000" +
    "\002\002\003\000\002\003\005\000\002\003\003\000\002" +
    "\004\003\000\002\004\003\000\002\004\003\000\002\004" +
    "\003\000\002\004\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\005\004\000" +
    "\002\006\003\000\002\006\003\000\002\006\003\000\002" +
    "\007\005\000\002\007\003\000\002\010\005\000\002\011" +
    "\004\000\002\012\005\000\002\012\003\000\002\013\004" +
    "\000\002\013\006\000\002\014\011\000\002\014\015\000" +
    "\002\015\015\000\002\015\017\000\002\016\010\000\002" +
    "\017\010\000\002\021\005\000\002\021\003\000\002\022" +
    "\003\000\002\022\003\000\002\023\006\000\002\023\005" +
    "\000\002\024\003\000\002\024\003\000\002\024\003\000" +
    "\002\024\003\000\002\024\003\000\002\024\003\000\002" +
    "\025\005\000\002\025\003\000\002\026\003\000\002\026" +
    "\003\000\002\027\005\000\002\027\003\000\002\030\003" +
    "\000\002\030\003\000\002\030\003\000\002\030\003\000" +
    "\002\031\005\000\002\031\003\000\002\031\003\000\002" +
    "\031\003\000\002\031\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\177\000\032\005\005\015\007\016\011\020\025\021" +
    "\013\030\006\032\020\033\032\037\030\040\023\041\021" +
    "\053\017\001\002\000\004\053\ufff4\001\002\000\006\021" +
    "\176\062\177\001\002\000\016\017\045\021\037\022\043" +
    "\044\114\061\044\062\046\001\002\000\006\002\ufffa\053" +
    "\170\001\002\000\004\053\uffee\001\002\000\016\017\045" +
    "\021\037\022\043\044\114\061\044\062\046\001\002\000" +
    "\004\053\152\001\002\000\004\025\150\001\002\000\004" +
    "\021\144\001\002\000\004\053\uffed\001\002\000\004\002" +
    "\143\001\002\000\032\002\ufff8\005\005\015\135\016\011" +
    "\020\025\021\013\030\006\032\020\033\032\037\030\040" +
    "\023\041\021\001\002\000\004\053\106\001\002\000\004" +
    "\021\uffe9\001\002\000\004\053\ufff6\001\002\000\004\021" +
    "\uffea\001\002\000\004\053\ufff3\001\002\000\014\017\045" +
    "\021\037\022\043\061\044\062\046\001\002\000\004\053" +
    "\ufff1\001\002\000\004\053\ufff5\001\002\000\004\021\uffeb" +
    "\001\002\000\004\053\uffef\001\002\000\004\021\035\001" +
    "\002\000\004\053\ufff0\001\002\000\004\053\ufff2\001\002" +
    "\000\004\025\036\001\002\000\014\017\045\021\037\022" +
    "\043\061\044\062\046\001\002\000\052\004\uffc1\006\uffc1" +
    "\007\uffc1\011\uffc1\012\uffc1\013\uffc1\014\uffc1\023\uffc1\026" +
    "\uffc1\034\uffc1\035\uffc1\042\uffc1\043\uffc1\045\uffc1\046\uffc1" +
    "\047\uffc1\050\uffc1\053\uffc1\054\uffc1\055\uffc1\001\002\000" +
    "\010\011\051\023\053\034\063\001\002\000\052\004\060" +
    "\006\057\007\uffcd\011\uffcd\012\uffcd\013\uffcd\014\uffcd\023" +
    "\uffcd\026\uffcd\034\uffcd\035\uffcd\042\uffcd\043\uffcd\045\uffcd" +
    "\046\uffcd\047\uffcd\050\061\053\uffcd\054\uffcd\055\056\001" +
    "\002\000\052\004\uffc9\006\uffc9\007\uffc9\011\uffc9\012\uffc9" +
    "\013\uffc9\014\uffc9\023\uffc9\026\uffc9\034\uffc9\035\uffc9\042" +
    "\uffc9\043\uffc9\045\uffc9\046\uffc9\047\uffc9\050\uffc9\053\uffc9" +
    "\054\uffc9\055\uffc9\001\002\000\052\004\uffc3\006\uffc3\007" +
    "\uffc3\011\uffc3\012\uffc3\013\uffc3\014\uffc3\023\uffc3\026\uffc3" +
    "\034\uffc3\035\uffc3\042\uffc3\043\uffc3\045\uffc3\046\uffc3\047" +
    "\uffc3\050\uffc3\053\uffc3\054\uffc3\055\uffc3\001\002\000\052" +
    "\004\uffc2\006\uffc2\007\uffc2\011\uffc2\012\uffc2\013\uffc2\014" +
    "\uffc2\023\uffc2\026\uffc2\034\uffc2\035\uffc2\042\uffc2\043\uffc2" +
    "\045\uffc2\046\uffc2\047\uffc2\050\uffc2\053\uffc2\054\uffc2\055" +
    "\uffc2\001\002\000\014\017\045\021\037\022\043\061\044" +
    "\062\046\001\002\000\052\004\uffc0\006\uffc0\007\uffc0\011" +
    "\uffc0\012\uffc0\013\uffc0\014\uffc0\023\uffc0\026\uffc0\034\uffc0" +
    "\035\uffc0\042\uffc0\043\uffc0\045\uffc0\046\uffc0\047\uffc0\050" +
    "\uffc0\053\uffc0\054\uffc0\055\uffc0\001\002\000\010\011\051" +
    "\012\050\023\053\001\002\000\052\004\uffc4\006\uffc4\007" +
    "\uffc4\011\uffc4\012\uffc4\013\uffc4\014\uffc4\023\uffc4\026\uffc4" +
    "\034\uffc4\035\uffc4\042\uffc4\043\uffc4\045\uffc4\046\uffc4\047" +
    "\uffc4\050\uffc4\053\uffc4\054\uffc4\055\uffc4\001\002\000\014" +
    "\017\uffcc\021\uffcc\022\uffcc\061\uffcc\062\uffcc\001\002\000" +
    "\014\017\045\021\037\022\043\061\044\062\046\001\002" +
    "\000\014\017\uffcb\021\uffcb\022\uffcb\061\uffcb\062\uffcb\001" +
    "\002\000\052\004\060\006\057\007\uffce\011\uffce\012\uffce" +
    "\013\uffce\014\uffce\023\uffce\026\uffce\034\uffce\035\uffce\042" +
    "\uffce\043\uffce\045\uffce\046\uffce\047\uffce\050\061\053\uffce" +
    "\054\uffce\055\056\001\002\000\014\017\045\021\037\022" +
    "\043\061\044\062\046\001\002\000\014\017\uffc6\021\uffc6" +
    "\022\uffc6\061\uffc6\062\uffc6\001\002\000\014\017\uffc7\021" +
    "\uffc7\022\uffc7\061\uffc7\062\uffc7\001\002\000\014\017\uffc8" +
    "\021\uffc8\022\uffc8\061\uffc8\062\uffc8\001\002\000\014\017" +
    "\uffc5\021\uffc5\022\uffc5\061\uffc5\062\uffc5\001\002\000\052" +
    "\004\uffca\006\uffca\007\uffca\011\uffca\012\uffca\013\uffca\014" +
    "\uffca\023\uffca\026\uffca\034\uffca\035\uffca\042\uffca\043\uffca" +
    "\045\uffca\046\uffca\047\uffca\050\uffca\053\uffca\054\uffca\055" +
    "\uffca\001\002\000\014\017\045\021\037\022\043\061\044" +
    "\062\046\001\002\000\012\011\051\023\053\035\065\053" +
    "\066\001\002\000\014\017\045\021\037\022\043\061\044" +
    "\062\046\001\002\000\026\005\005\016\011\020\025\021" +
    "\013\030\006\032\020\033\032\037\030\040\023\041\021" +
    "\001\002\000\004\053\070\001\002\000\030\005\005\016" +
    "\011\020\025\021\013\030\006\032\020\033\032\036\072" +
    "\037\030\040\023\041\021\001\002\000\004\053\ufff7\001" +
    "\002\000\004\021\073\001\002\000\004\053\uffde\001\002" +
    "\000\010\011\051\023\053\053\075\001\002\000\026\005" +
    "\005\016\011\020\025\021\013\030\006\032\020\033\032" +
    "\037\030\040\023\041\021\001\002\000\004\053\077\001" +
    "\002\000\030\005\005\016\011\020\025\021\013\030\006" +
    "\032\020\033\032\036\100\037\030\040\023\041\021\001" +
    "\002\000\004\021\101\001\002\000\004\053\uffdd\001\002" +
    "\000\006\014\104\053\uffe5\001\002\000\012\011\051\014" +
    "\uffe3\023\053\053\uffe3\001\002\000\014\017\045\021\037" +
    "\022\043\061\044\062\046\001\002\000\012\011\051\014" +
    "\uffe4\023\053\053\uffe4\001\002\000\026\005\005\016\011" +
    "\020\025\021\013\030\006\032\020\033\032\037\030\040" +
    "\023\041\021\001\002\000\004\053\110\001\002\000\030" +
    "\005\005\016\011\020\025\021\013\024\111\030\006\032" +
    "\020\033\032\037\030\040\023\041\021\001\002\000\016" +
    "\017\045\021\037\022\043\044\114\061\044\062\046\001" +
    "\002\000\022\007\123\011\051\023\053\026\122\045\125" +
    "\046\124\047\117\054\121\001\002\000\010\042\130\043" +
    "\131\053\uffdc\001\002\000\014\017\045\021\037\022\043" +
    "\061\044\062\046\001\002\000\012\013\uffd9\042\uffd9\043" +
    "\uffd9\053\uffd9\001\002\000\022\007\123\011\051\023\053" +
    "\026\122\045\125\046\124\047\117\054\121\001\002\000" +
    "\014\017\uffcf\021\uffcf\022\uffcf\061\uffcf\062\uffcf\001\002" +
    "\000\014\017\045\021\037\022\043\061\044\062\046\001" +
    "\002\000\014\017\uffd3\021\uffd3\022\uffd3\061\uffd3\062\uffd3" +
    "\001\002\000\014\017\uffd4\021\uffd4\022\uffd4\061\uffd4\062" +
    "\uffd4\001\002\000\014\017\uffd2\021\uffd2\022\uffd2\061\uffd2" +
    "\062\uffd2\001\002\000\014\017\uffd0\021\uffd0\022\uffd0\061" +
    "\uffd0\062\uffd0\001\002\000\014\017\uffd1\021\uffd1\022\uffd1" +
    "\061\uffd1\062\uffd1\001\002\000\016\011\051\013\uffd6\023" +
    "\053\042\uffd6\043\uffd6\053\uffd6\001\002\000\016\017\045" +
    "\021\037\022\043\044\114\061\044\062\046\001\002\000" +
    "\016\017\uffd8\021\uffd8\022\uffd8\044\uffd8\061\uffd8\062\uffd8" +
    "\001\002\000\016\017\uffd7\021\uffd7\022\uffd7\044\uffd7\061" +
    "\uffd7\062\uffd7\001\002\000\012\013\uffda\042\uffda\043\uffda" +
    "\053\uffda\001\002\000\014\017\045\021\037\022\043\061" +
    "\044\062\046\001\002\000\016\011\051\013\uffd5\023\053" +
    "\042\uffd5\043\uffd5\053\uffd5\001\002\000\006\002\ufffc\053" +
    "\142\001\002\000\004\053\137\001\002\000\030\005\005" +
    "\015\140\016\011\020\025\021\013\030\006\032\020\033" +
    "\032\037\030\040\023\041\021\001\002\000\006\002\ufffe" +
    "\053\141\001\002\000\004\002\ufffd\001\002\000\004\002" +
    "\ufffb\001\002\000\004\002\000\001\002\000\006\053\uffe7" +
    "\060\uffe7\001\002\000\006\053\uffec\060\146\001\002\000" +
    "\004\021\147\001\002\000\006\053\uffe8\060\uffe8\001\002" +
    "\000\014\017\045\021\037\022\043\061\044\062\046\001" +
    "\002\000\010\011\051\023\053\053\uffe6\001\002\000\030" +
    "\005\005\015\153\016\011\020\025\021\013\030\006\032" +
    "\020\033\032\037\030\040\023\041\021\001\002\000\006" +
    "\002\001\053\154\001\002\000\004\002\uffff\001\002\000" +
    "\010\013\156\042\130\043\131\001\002\000\004\053\157" +
    "\001\002\000\026\005\005\016\011\020\025\021\013\030" +
    "\006\032\020\033\032\037\030\040\023\041\021\001\002" +
    "\000\004\053\161\001\002\000\032\005\005\010\162\016" +
    "\011\020\025\021\013\027\163\030\006\032\020\033\032" +
    "\037\030\040\023\041\021\001\002\000\004\053\164\001" +
    "\002\000\004\053\uffe0\001\002\000\026\005\005\016\011" +
    "\020\025\021\013\030\006\032\020\033\032\037\030\040" +
    "\023\041\021\001\002\000\004\053\166\001\002\000\030" +
    "\005\005\016\011\020\025\021\013\027\167\030\006\032" +
    "\020\033\032\037\030\040\023\041\021\001\002\000\004" +
    "\053\uffdf\001\002\000\004\002\ufff9\001\002\000\010\042" +
    "\130\043\131\053\172\001\002\000\026\005\005\016\011" +
    "\020\025\021\013\030\006\032\020\033\032\037\030\040" +
    "\023\041\021\001\002\000\004\053\174\001\002\000\030" +
    "\005\005\016\011\020\025\021\013\030\006\031\175\032" +
    "\020\033\032\037\030\040\023\041\021\001\002\000\004" +
    "\053\uffdb\001\002\000\004\053\uffe2\001\002\000\004\060" +
    "\200\001\002\000\004\021\201\001\002\000\004\053\uffe1" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\177\000\034\002\015\003\011\004\021\005\026\006" +
    "\013\010\003\011\023\013\033\014\025\015\032\016\030" +
    "\017\007\020\014\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\021\170\023\114\025\111\027\040\031\041" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\021" +
    "\154\023\114\025\111\027\040\031\041\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\007\144\001\001\000" +
    "\002\001\001\000\002\001\001\000\032\003\135\004\021" +
    "\005\026\006\013\010\003\011\023\013\033\014\025\015" +
    "\032\016\030\017\007\020\014\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\012\101\025\102\027\040\031\041" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\025\037\027" +
    "\040\031\041\001\001\000\002\001\001\000\004\026\051" +
    "\001\001\000\004\030\054\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\025\046\027\040" +
    "\031\041\001\001\000\002\001\001\000\004\026\051\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\027\053" +
    "\031\041\001\001\000\002\001\001\000\004\030\054\001" +
    "\001\000\004\031\061\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\025\063\027\040\031\041\001\001\000\004" +
    "\026\051\001\001\000\010\025\073\027\040\031\041\001" +
    "\001\000\032\003\066\004\021\005\026\006\013\010\003" +
    "\011\023\013\033\014\025\015\032\016\030\017\007\020" +
    "\014\001\001\000\002\001\001\000\030\004\070\005\026" +
    "\006\013\010\003\011\023\013\033\014\025\015\032\016" +
    "\030\017\007\020\014\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\026\051\001\001\000" +
    "\032\003\075\004\021\005\026\006\013\010\003\011\023" +
    "\013\033\014\025\015\032\016\030\017\007\020\014\001" +
    "\001\000\002\001\001\000\030\004\070\005\026\006\013" +
    "\010\003\011\023\013\033\014\025\015\032\016\030\017" +
    "\007\020\014\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\026\051\001\001\000\010\025" +
    "\104\027\040\031\041\001\001\000\004\026\051\001\001" +
    "\000\032\003\106\004\021\005\026\006\013\010\003\011" +
    "\023\013\033\014\025\015\032\016\030\017\007\020\014" +
    "\001\001\000\002\001\001\000\030\004\070\005\026\006" +
    "\013\010\003\011\023\013\033\014\025\015\032\016\030" +
    "\017\007\020\014\001\001\000\014\021\112\023\114\025" +
    "\111\027\040\031\041\001\001\000\006\024\132\026\051" +
    "\001\001\000\004\022\126\001\001\000\010\025\115\027" +
    "\040\031\041\001\001\000\002\001\001\000\006\024\117" +
    "\026\051\001\001\000\002\001\001\000\010\025\125\027" +
    "\040\031\041\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\026\051\001\001\000\012\023\131\025\111\027\040" +
    "\031\041\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\025\133\027\040\031\041\001\001" +
    "\000\004\026\051\001\001\000\002\001\001\000\002\001" +
    "\001\000\030\004\070\005\026\006\013\010\003\011\023" +
    "\013\033\014\025\015\032\016\030\017\007\020\014\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\025\150\027\040" +
    "\031\041\001\001\000\004\026\051\001\001\000\030\004" +
    "\070\005\026\006\013\010\003\011\023\013\033\014\025" +
    "\015\032\016\030\017\007\020\014\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\022\126\001\001\000\002" +
    "\001\001\000\032\003\157\004\021\005\026\006\013\010" +
    "\003\011\023\013\033\014\025\015\032\016\030\017\007" +
    "\020\014\001\001\000\002\001\001\000\030\004\070\005" +
    "\026\006\013\010\003\011\023\013\033\014\025\015\032" +
    "\016\030\017\007\020\014\001\001\000\002\001\001\000" +
    "\002\001\001\000\032\003\164\004\021\005\026\006\013" +
    "\010\003\011\023\013\033\014\025\015\032\016\030\017" +
    "\007\020\014\001\001\000\002\001\001\000\030\004\070" +
    "\005\026\006\013\010\003\011\023\013\033\014\025\015" +
    "\032\016\030\017\007\020\014\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\022\126\001\001\000\032\003" +
    "\172\004\021\005\026\006\013\010\003\011\023\013\033" +
    "\014\025\015\032\016\030\017\007\020\014\001\001\000" +
    "\002\001\001\000\030\004\070\005\026\006\013\010\003" +
    "\011\023\013\033\014\025\015\032\016\030\017\007\020" +
    "\014\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




  public static void main(String args[]) throws Exception{
    parser sintactico;
	
	if(args.length>0){
		sintactico = new parser(new Scanner(new FileInputStream(args[0])));
		sintactico.parse();
	}else{
		System.out.println("No se encontró el código fuente (Parámetro incorrecto)");
	}
    
  }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // factor ::= CADENA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // factor ::= ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // factor ::= NUM_FLOTANTE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // factor ::= NUM_ENTERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // factor ::= LPAREN expresion_simple RPAREN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // op_mult ::= CIRCUMFLEX 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // op_mult ::= MODULE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // op_mult ::= SLASH 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // op_mult ::= ASTERISK 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // term ::= factor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // term ::= term op_mult factor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // op_suma ::= MINUS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_suma",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // op_suma ::= PLUS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_suma",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expresion_simple ::= term 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_simple",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresion_simple ::= expresion_simple op_suma term 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_simple",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // op_comparacion ::= GREATER_THAN_EQ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // op_comparacion ::= GREATER_THAN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // op_comparacion ::= LESS_THAN_EQ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // op_comparacion ::= LESS_THAN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // op_comparacion ::= DIFFERENT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // op_comparacion ::= EQUAL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expresion_comparacion ::= expresion_simple op_comparacion expresion_simple 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_comparacion",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expresion_comparacion ::= NOT expresion_simple op_comparacion expresion_simple 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_comparacion",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // op_logico ::= OR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_logico",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // op_logico ::= AND 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_logico",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expresion_compuesta ::= expresion_comparacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_compuesta",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expresion_compuesta ::= expresion_compuesta op_logico expresion_comparacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_compuesta",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // sent_while ::= WHILE expresion_compuesta NEW_LINE secuencia_sent NEW_LINE ENDWHILE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_while",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // sent_do ::= DO NEW_LINE secuencia_sent NEW_LINE LOOP_UNTIL expresion_compuesta 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_do",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // sent_for ::= FOR ID ASSIGN expresion_simple TO expresion_simple STEP expresion_simple NEW_LINE secuencia_sent NEW_LINE NEXT ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_for",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-12)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // sent_for ::= FOR ID ASSIGN expresion_simple TO expresion_simple NEW_LINE secuencia_sent NEW_LINE NEXT ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_for",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // sent_if ::= IF expresion_compuesta THEN NEW_LINE secuencia_sent NEW_LINE ELSE NEW_LINE secuencia_sent NEW_LINE ENDIF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_if",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // sent_if ::= IF expresion_compuesta THEN NEW_LINE secuencia_sent NEW_LINE ENDIF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_if",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // sent_leer ::= INPUT CADENA COMMA ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_leer",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // sent_leer ::= INPUT ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_leer",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // list_impresion ::= expresion_simple 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_impresion",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // list_impresion ::= list_impresion CONCAT expresion_simple 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_impresion",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sent_escribir ::= PRINT list_impresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_escribir",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // sent_asignacion ::= ID ASSIGN expresion_simple 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_asignacion",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // list_var ::= ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_var",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // list_var ::= list_var COMMA ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_var",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipo_dato ::= STRING 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipo_dato ::= FLOAT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // tipo_dato ::= INTEGER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // sent_declaracion ::= tipo_dato list_var 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_declaracion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // sentencia ::= sent_proc 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // sentencia ::= sent_while 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // sentencia ::= sent_do 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sentencia ::= sent_for 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // sentencia ::= sent_if 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // sentencia ::= sent_leer 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencia ::= sent_escribir 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentencia ::= sent_asignacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sentencia ::= sent_declaracion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // secuencia_sent ::= sentencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("secuencia_sent",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // secuencia_sent ::= secuencia_sent NEW_LINE sentencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("secuencia_sent",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // programa ::= NEW_LINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // programa ::= END NEW_LINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // programa ::= END 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // programa ::= NEW_LINE END NEW_LINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // programa ::= NEW_LINE END 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // programa ::= NEW_LINE secuencia_sent NEW_LINE END NEW_LINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // programa ::= NEW_LINE secuencia_sent NEW_LINE END 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= secuencia_sent NEW_LINE END NEW_LINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // programa ::= secuencia_sent NEW_LINE END 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

