/* The following code was generated by JFlex 1.4.1 on 10/10/11 2:27 */


import java.io.FileInputStream;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 10/10/11 2:27 from the specification file
 * <tt>C:/Users/admin/Desktop/Interprete-basic/lexico/lexico.flex</tt>
 */
class Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  3,  0,  0,  4,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    19,  0,  6,  0,  0, 32,  0,  0, 34, 35, 31, 29,  0, 30,  0, 32, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0, 38, 26, 28, 27,  0, 
     0,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 36,  0, 37, 33,  0, 
     0, 24,  2,  2,  9,  7, 11, 23, 13, 10,  2,  2, 14, 25,  8, 17, 
    18,  2, 21, 15, 12, 20,  2, 16, 22,  2,  2,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\1\1\4\1\5"+
    "\15\1\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\3"+
    "\4\23\1\24\1\23\1\25\3\23\1\26\3\23\1\27"+
    "\3\23\1\30\1\31\1\32\1\33\1\34\2\23\1\35"+
    "\3\23\1\36\6\23\1\37\1\40\2\23\1\41\1\42"+
    "\3\23\1\43\1\23\1\44\3\23\1\45\2\23\1\46"+
    "\1\47\1\0\1\23\1\50\1\51\2\23\1\0\1\52"+
    "\1\23\1\53\1\0\1\54\2\0\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\234\0\303\0\352\0\47"+
    "\0\u0111\0\u0138\0\u015f\0\u0186\0\u01ad\0\u01d4\0\u01fb\0\u0222"+
    "\0\u0249\0\u0270\0\u0297\0\u02be\0\u02e5\0\u030c\0\u0333\0\u035a"+
    "\0\47\0\47\0\47\0\47\0\47\0\47\0\47\0\47"+
    "\0\47\0\47\0\165\0\47\0\u0381\0\u03a8\0\u03cf\0\u03f6"+
    "\0\165\0\u041d\0\165\0\u0444\0\u046b\0\u0492\0\165\0\u04b9"+
    "\0\u04e0\0\u0507\0\165\0\u052e\0\u0555\0\u057c\0\47\0\47"+
    "\0\47\0\47\0\u05a3\0\u05ca\0\u05f1\0\165\0\u0618\0\u063f"+
    "\0\u0666\0\165\0\u068d\0\u06b4\0\u06db\0\u0702\0\u0729\0\u0750"+
    "\0\165\0\165\0\u0777\0\u079e\0\165\0\165\0\u07c5\0\u07ec"+
    "\0\u0813\0\165\0\u083a\0\165\0\u0861\0\u0888\0\u08af\0\165"+
    "\0\u08d6\0\u08fd\0\165\0\165\0\u0924\0\u094b\0\165\0\165"+
    "\0\u0972\0\u0999\0\u09c0\0\165\0\u09e7\0\165\0\u0a0e\0\165"+
    "\0\u0a35\0\u0a5c\0\47";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\4\1\17\1\20"+
    "\1\21\1\22\1\23\1\7\1\4\1\24\2\4\1\25"+
    "\1\4\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\50\0\1\3"+
    "\46\0\2\43\4\0\14\43\1\0\6\43\21\0\1\44"+
    "\45\0\1\44\50\0\1\7\15\0\1\7\24\0\2\43"+
    "\4\0\1\43\1\45\5\43\1\46\4\43\1\0\6\43"+
    "\16\0\2\43\4\0\1\47\11\43\1\50\1\43\1\0"+
    "\6\43\16\0\2\43\4\0\12\43\1\51\1\43\1\0"+
    "\6\43\16\0\2\43\4\0\1\43\1\52\2\43\1\53"+
    "\7\43\1\0\6\43\16\0\2\43\4\0\7\43\1\54"+
    "\2\43\1\55\1\43\1\0\6\43\16\0\2\43\4\0"+
    "\6\43\1\56\3\43\1\57\1\43\1\0\6\43\16\0"+
    "\2\43\4\0\12\43\1\60\1\43\1\0\6\43\16\0"+
    "\2\43\4\0\5\43\1\61\6\43\1\0\6\43\16\0"+
    "\2\43\4\0\6\43\1\62\5\43\1\0\6\43\16\0"+
    "\2\43\4\0\14\43\1\0\1\43\1\63\4\43\16\0"+
    "\2\43\4\0\14\43\1\0\1\43\1\64\4\43\16\0"+
    "\2\43\4\0\1\65\13\43\1\0\6\43\16\0\2\43"+
    "\4\0\1\43\1\66\12\43\1\0\6\43\50\0\1\67"+
    "\1\70\46\0\1\71\46\0\1\72\13\0\2\43\4\0"+
    "\2\43\1\73\11\43\1\0\6\43\16\0\2\43\4\0"+
    "\10\43\1\74\3\43\1\0\6\43\16\0\2\43\4\0"+
    "\14\43\1\0\2\43\1\75\3\43\16\0\2\43\4\0"+
    "\5\43\1\76\6\43\1\0\6\43\16\0\2\43\4\0"+
    "\5\43\1\77\5\43\1\100\1\0\6\43\16\0\2\43"+
    "\4\0\12\43\1\101\1\43\1\0\6\43\16\0\2\43"+
    "\4\0\14\43\1\0\1\43\1\102\4\43\16\0\2\43"+
    "\4\0\1\103\13\43\1\0\6\43\16\0\2\43\4\0"+
    "\12\43\1\104\1\43\1\0\6\43\16\0\2\43\4\0"+
    "\1\105\13\43\1\0\1\43\1\106\4\43\16\0\2\43"+
    "\4\0\3\43\1\107\10\43\1\0\6\43\16\0\2\43"+
    "\4\0\3\43\1\110\10\43\1\0\6\43\16\0\2\43"+
    "\4\0\14\43\1\0\5\43\1\111\16\0\2\43\4\0"+
    "\2\43\1\112\11\43\1\0\6\43\16\0\2\43\4\0"+
    "\3\43\1\113\5\43\1\114\2\43\1\0\6\43\16\0"+
    "\2\43\4\0\1\115\13\43\1\0\6\43\16\0\2\43"+
    "\4\0\5\43\1\116\6\43\1\0\6\43\16\0\2\43"+
    "\4\0\1\117\13\43\1\0\6\43\16\0\2\43\4\0"+
    "\14\43\1\0\1\120\5\43\16\0\2\43\4\0\14\43"+
    "\1\0\4\43\1\121\1\43\16\0\2\43\4\0\1\43"+
    "\1\122\12\43\1\0\6\43\16\0\2\43\4\0\13\43"+
    "\1\123\1\0\6\43\16\0\2\43\4\0\13\43\1\124"+
    "\1\0\6\43\16\0\2\43\4\0\3\43\1\125\10\43"+
    "\1\0\6\43\16\0\2\43\4\0\7\43\1\126\4\43"+
    "\1\0\6\43\16\0\2\43\4\0\1\43\1\127\12\43"+
    "\1\0\6\43\16\0\2\43\4\0\4\43\1\130\7\43"+
    "\1\0\6\43\16\0\2\43\4\0\6\43\1\131\5\43"+
    "\1\0\6\43\16\0\2\43\4\0\14\43\1\0\3\43"+
    "\1\132\2\43\16\0\2\43\4\0\5\43\1\133\6\43"+
    "\1\0\6\43\16\0\2\43\4\0\5\43\1\134\6\43"+
    "\1\0\6\43\16\0\2\43\4\0\14\43\1\135\6\43"+
    "\16\0\2\43\4\0\1\43\1\136\12\43\1\0\6\43"+
    "\16\0\2\43\4\0\1\137\13\43\1\0\6\43\16\0"+
    "\2\43\4\0\5\43\1\140\6\43\1\0\6\43\16\0"+
    "\2\43\4\0\3\43\1\141\10\43\1\0\6\43\16\0"+
    "\2\43\4\0\1\142\13\43\1\0\6\43\41\0\1\143"+
    "\23\0\2\43\4\0\14\43\1\0\3\43\1\144\2\43"+
    "\16\0\2\43\4\0\7\43\1\145\4\43\1\0\6\43"+
    "\16\0\2\43\4\0\14\43\1\0\1\43\1\146\4\43"+
    "\25\0\1\147\37\0\2\43\4\0\1\150\13\43\1\0"+
    "\6\43\31\0\1\151\44\0\1\152\52\0\1\153\30\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2691];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\20\1\12\11\1\1\1\11"+
    "\22\1\4\11\42\1\1\0\5\1\1\0\3\1\1\0"+
    "\1\1\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
	private int lineanum=0;
	private boolean debug=true;
	static String fname ; //nombre archivo entrada

	public static void main(String argv[])throws java.io.IOException {
		int numparams = argv.length; //número argumentos pasados
		if ( numparams != 1) 
		{ 	//error: nr. Parámetros incorrecto
			System.out.println ("Número parámetros incorrecto!");
			System.out.println ( "\t Uso: java yylex code.bas");
			return; 
		}
		else 
		{ 	
			fname = argv[0];
			
			/*	Comprobando extensión .bas	*/
			if(fname.substring(fname.length()-3, fname.length()).equals("bas")){
				Scanner lexico = new Scanner(new FileInputStream(fname));
				while (lexico.yylex() != sym.END);
			}else{
				System.out.println ("Extensión de archivo incorrecto!");
				System.out.println ( "\tEj: code.bas");
			}
		}
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Integer yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 44: 
          { if(debug) System.out.println("token ENDWHILE");
			return sym.ENDWHILE;
          }
        case 46: break;
        case 42: 
          { if(debug) System.out.println("token STRING");
			return sym.STRING;
          }
        case 47: break;
        case 5: 
          { if(debug) System.out.println("token QMARK");
			return sym.QMARK;
          }
        case 48: break;
        case 33: 
          { if(debug) System.out.println("token ELSE");
			return sym.ELSE;
          }
        case 49: break;
        case 35: 
          { if(debug) System.out.println("token THEN");
			return sym.THEN;
          }
        case 50: break;
        case 30: 
          { if(debug) System.out.println("token FOR");
			return sym.FOR;
          }
        case 51: break;
        case 14: 
          { if(debug) System.out.println("token LPAREN");
			return sym.LPAREN;
          }
        case 52: break;
        case 23: 
          { if(debug) System.out.println("token OR");
			return sym.OR;
          }
        case 53: break;
        case 37: 
          { if(debug) System.out.println("token ENDIF");
			return sym.ENDIF;
          }
        case 54: break;
        case 43: 
          { if(debug) System.out.println("token INTEGER");
			return sym.INTEGER;
          }
        case 55: break;
        case 21: 
          { if(debug) System.out.println("token IF");
			return sym.IF;
          }
        case 56: break;
        case 45: 
          { if(debug) System.out.println("token LOOP_UNTIL");
			return sym.LOOP_UNTIL;
          }
        case 57: break;
        case 4: 
          { /* saltos espacios en blanco*/
          }
        case 58: break;
        case 40: 
          { if(debug) System.out.println("token WHILE");
			return sym.WHILE;
          }
        case 59: break;
        case 27: 
          { if(debug) System.out.println("token EQUAL");
			return sym.EQUAL;
          }
        case 60: break;
        case 31: 
          { if(debug) System.out.println("token COMENTARIO"); /*No tomo en cuenta los comentarios*/
          }
        case 61: break;
        case 12: 
          { if(debug) System.out.println("token SLASH");
			return sym.SLASH;
          }
        case 62: break;
        case 34: 
          { if(debug) System.out.println("token NEXT");
			return sym.NEXT;
          }
        case 63: break;
        case 17: 
          { if(debug) System.out.println("token RPOPPER");
			return sym.RPOPPER;
          }
        case 64: break;
        case 32: 
          { if(debug) System.out.println("token AND");
			return sym.AND;
          }
        case 65: break;
        case 13: 
          { if(debug) System.out.println("token CIRCUMFLEX");
			return sym.CIRCUMFLEX;
          }
        case 66: break;
        case 1: 
          { System.err.println("Caracter Ilegal encontrado en analisis lexico: " + yytext() + "\n");
          }
        case 67: break;
        case 26: 
          { if(debug) System.out.println("token GREATER_THAN_EQ");
			return sym.GREATER_THAN_EQ;
          }
        case 68: break;
        case 39: 
          { if(debug) System.out.println("token FLOAT");
			return sym.FLOAT;
          }
        case 69: break;
        case 7: 
          { if(debug) System.out.println("token GREATER_THAN");
			return sym.GREATER_THAN;
          }
        case 70: break;
        case 16: 
          { if(debug) System.out.println("token LPOPPER");
			return sym.LPOPPER;
          }
        case 71: break;
        case 41: 
          { if(debug) System.out.println("token PRINT");
			return sym.PRINT;
          }
        case 72: break;
        case 24: 
          { if(debug) System.out.println("token DIFFERENT");
			return sym.LESS_THAN_EQ;
          }
        case 73: break;
        case 18: 
          { if(debug) System.out.println("token CONCAT");
			return sym.CONCAT;
          }
        case 74: break;
        case 6: 
          { if(debug) System.out.println("token LESS_THAN");
			return sym.LESS_THAN;
          }
        case 75: break;
        case 10: 
          { if(debug) System.out.println("token MINUS");
			return sym.MINUS;
          }
        case 76: break;
        case 11: 
          { if(debug) System.out.println("token ASTERISK");
			return sym.ASTERISK;
          }
        case 77: break;
        case 22: 
          { if(debug) System.out.println("token TO");
			return sym.TO;
          }
        case 78: break;
        case 20: 
          { if(debug) System.out.println("token DO");
			return sym.DO;
          }
        case 79: break;
        case 2: 
          { if(debug) System.out.println("token NUM");
			return sym.NUM;
          }
        case 80: break;
        case 36: 
          { if(debug) System.out.println("token STEP");
			return sym.STEP;
          }
        case 81: break;
        case 9: 
          { if(debug) System.out.println("token PLUS");
			return sym.PLUS;
          }
        case 82: break;
        case 15: 
          { if(debug) System.out.println("token RPAREN");
			return sym.RPAREN;
          }
        case 83: break;
        case 19: 
          { if(debug) System.out.println("token ID");
				return sym.ID;
          }
        case 84: break;
        case 3: 
          { lineanum++;
          }
        case 85: break;
        case 28: 
          { if(debug) System.out.println("token END");
			return sym.END;
          }
        case 86: break;
        case 8: 
          { if(debug) System.out.println("token ASSIGN");
			return sym.ASSIGN;
          }
        case 87: break;
        case 38: 
          { if(debug) System.out.println("token INPUT");
			return sym.INPUT;
          }
        case 88: break;
        case 25: 
          { if(debug) System.out.println("token LESS_THAN_EQ");
			return sym.LESS_THAN_EQ;
          }
        case 89: break;
        case 29: 
          { if(debug) System.out.println("token NOT");
			return sym.NOT;
          }
        case 90: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {     return sym.EOF;
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
