
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 03 00:17:07 VET 2011
//----------------------------------------------------

package sintactico;

import arbol.*;
import arbol.Nodo.TIPO;
import arbol.Variable.DATO;
import arbol.Operacion.OP;
import lexico.Scanner;
import java.io.FileInputStream;
import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Thu Nov 03 00:17:07 VET 2011
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\124\000\002\002\005\000\002\002\004\000\002\002" +
    "\006\000\002\002\006\000\002\002\007\000\002\002\007" +
    "\000\002\002\010\000\002\002\010\000\002\002\011\000" +
    "\002\002\003\000\002\002\004\000\002\002\005\000\002" +
    "\002\005\000\002\002\006\000\002\002\006\000\002\002" +
    "\007\000\002\002\003\000\002\003\005\000\002\003\003" +
    "\000\002\004\005\000\002\004\003\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\005\003\000\002\005\003\000\002\005" +
    "\003\000\002\005\003\000\002\006\004\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\010\005\000" +
    "\002\010\010\000\002\010\006\000\002\010\003\000\002" +
    "\011\005\000\002\011\010\000\002\012\004\000\002\013" +
    "\005\000\002\013\003\000\002\014\004\000\002\014\006" +
    "\000\002\015\011\000\002\015\015\000\002\016\015\000" +
    "\002\016\017\000\002\017\010\000\002\020\010\000\002" +
    "\021\012\000\002\021\013\000\002\023\006\000\002\023" +
    "\004\000\002\022\006\000\002\022\005\000\002\024\005" +
    "\000\002\024\003\000\002\025\003\000\002\025\003\000" +
    "\002\026\006\000\002\026\005\000\002\027\003\000\002" +
    "\027\003\000\002\027\003\000\002\027\003\000\002\027" +
    "\003\000\002\027\003\000\002\030\005\000\002\030\003" +
    "\000\002\031\003\000\002\031\003\000\002\032\005\000" +
    "\002\032\003\000\002\033\003\000\002\033\003\000\002" +
    "\033\003\000\002\033\003\000\002\034\005\000\002\034" +
    "\003\000\002\034\003\000\002\034\003\000\002\034\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\254\000\034\003\026\005\005\015\007\016\011\020" +
    "\025\021\015\030\006\032\020\033\033\037\032\040\023" +
    "\041\021\053\017\001\002\000\004\053\uffeb\001\002\000" +
    "\006\021\253\062\254\001\002\000\016\017\046\021\040" +
    "\022\045\044\116\061\042\062\047\001\002\000\006\002" +
    "\ufff8\053\243\001\002\000\004\053\uffe5\001\002\000\016" +
    "\017\046\021\040\022\045\044\116\061\042\062\047\001" +
    "\002\000\004\053\uffe4\001\002\000\004\053\223\001\002" +
    "\000\004\021\202\001\002\000\010\017\177\025\200\051" +
    "\176\001\002\000\004\002\175\001\002\000\030\005\005" +
    "\015\136\016\011\020\025\021\015\030\006\032\020\033" +
    "\033\037\032\040\023\041\021\001\002\000\004\053\107" +
    "\001\002\000\004\021\uffe0\001\002\000\004\053\uffed\001" +
    "\002\000\004\021\uffe1\001\002\000\004\053\uffea\001\002" +
    "\000\014\017\046\021\040\022\045\061\042\062\047\001" +
    "\002\000\004\002\ufff1\001\002\000\004\053\uffe8\001\002" +
    "\000\004\053\uffec\001\002\000\004\053\uffe6\001\002\000" +
    "\004\021\uffe2\001\002\000\004\021\036\001\002\000\004" +
    "\053\uffe7\001\002\000\004\053\uffe9\001\002\000\004\025" +
    "\037\001\002\000\014\017\046\021\040\022\045\061\042" +
    "\062\047\001\002\000\052\004\uffaf\006\uffaf\007\uffaf\011" +
    "\uffaf\012\uffaf\013\uffaf\014\uffaf\023\uffaf\026\uffaf\034\uffaf" +
    "\035\uffaf\042\uffaf\043\uffaf\045\uffaf\046\uffaf\047\uffaf\050" +
    "\uffaf\053\uffaf\054\uffaf\055\uffaf\001\002\000\010\011\053" +
    "\023\054\034\064\001\002\000\052\004\uffb0\006\uffb0\007" +
    "\uffb0\011\uffb0\012\uffb0\013\uffb0\014\uffb0\023\uffb0\026\uffb0" +
    "\034\uffb0\035\uffb0\042\uffb0\043\uffb0\045\uffb0\046\uffb0\047" +
    "\uffb0\050\uffb0\053\uffb0\054\uffb0\055\uffb0\001\002\000\052" +
    "\004\061\006\060\007\uffbb\011\uffbb\012\uffbb\013\uffbb\014" +
    "\uffbb\023\uffbb\026\uffbb\034\uffbb\035\uffbb\042\uffbb\043\uffbb" +
    "\045\uffbb\046\uffbb\047\uffbb\050\062\053\uffbb\054\uffbb\055" +
    "\057\001\002\000\052\004\uffb7\006\uffb7\007\uffb7\011\uffb7" +
    "\012\uffb7\013\uffb7\014\uffb7\023\uffb7\026\uffb7\034\uffb7\035" +
    "\uffb7\042\uffb7\043\uffb7\045\uffb7\046\uffb7\047\uffb7\050\uffb7" +
    "\053\uffb7\054\uffb7\055\uffb7\001\002\000\052\004\uffb1\006" +
    "\uffb1\007\uffb1\011\uffb1\012\uffb1\013\uffb1\014\uffb1\023\uffb1" +
    "\026\uffb1\034\uffb1\035\uffb1\042\uffb1\043\uffb1\045\uffb1\046" +
    "\uffb1\047\uffb1\050\uffb1\053\uffb1\054\uffb1\055\uffb1\001\002" +
    "\000\014\017\046\021\040\022\045\061\042\062\047\001" +
    "\002\000\052\004\uffae\006\uffae\007\uffae\011\uffae\012\uffae" +
    "\013\uffae\014\uffae\023\uffae\026\uffae\034\uffae\035\uffae\042" +
    "\uffae\043\uffae\045\uffae\046\uffae\047\uffae\050\uffae\053\uffae" +
    "\054\uffae\055\uffae\001\002\000\010\011\053\012\051\023" +
    "\054\001\002\000\052\004\uffb2\006\uffb2\007\uffb2\011\uffb2" +
    "\012\uffb2\013\uffb2\014\uffb2\023\uffb2\026\uffb2\034\uffb2\035" +
    "\uffb2\042\uffb2\043\uffb2\045\uffb2\046\uffb2\047\uffb2\050\uffb2" +
    "\053\uffb2\054\uffb2\055\uffb2\001\002\000\014\017\046\021" +
    "\040\022\045\061\042\062\047\001\002\000\014\017\uffba" +
    "\021\uffba\022\uffba\061\uffba\062\uffba\001\002\000\014\017" +
    "\uffb9\021\uffb9\022\uffb9\061\uffb9\062\uffb9\001\002\000\052" +
    "\004\061\006\060\007\uffbc\011\uffbc\012\uffbc\013\uffbc\014" +
    "\uffbc\023\uffbc\026\uffbc\034\uffbc\035\uffbc\042\uffbc\043\uffbc" +
    "\045\uffbc\046\uffbc\047\uffbc\050\062\053\uffbc\054\uffbc\055" +
    "\057\001\002\000\014\017\046\021\040\022\045\061\042" +
    "\062\047\001\002\000\014\017\uffb4\021\uffb4\022\uffb4\061" +
    "\uffb4\062\uffb4\001\002\000\014\017\uffb5\021\uffb5\022\uffb5" +
    "\061\uffb5\062\uffb5\001\002\000\014\017\uffb6\021\uffb6\022" +
    "\uffb6\061\uffb6\062\uffb6\001\002\000\014\017\uffb3\021\uffb3" +
    "\022\uffb3\061\uffb3\062\uffb3\001\002\000\052\004\uffb8\006" +
    "\uffb8\007\uffb8\011\uffb8\012\uffb8\013\uffb8\014\uffb8\023\uffb8" +
    "\026\uffb8\034\uffb8\035\uffb8\042\uffb8\043\uffb8\045\uffb8\046" +
    "\uffb8\047\uffb8\050\uffb8\053\uffb8\054\uffb8\055\uffb8\001\002" +
    "\000\014\017\046\021\040\022\045\061\042\062\047\001" +
    "\002\000\012\011\053\023\054\035\066\053\067\001\002" +
    "\000\014\017\046\021\040\022\045\061\042\062\047\001" +
    "\002\000\026\005\005\016\011\020\025\021\015\030\006" +
    "\032\020\033\033\037\032\040\023\041\021\001\002\000" +
    "\004\053\071\001\002\000\030\005\005\016\011\020\025" +
    "\021\015\030\006\032\020\033\033\036\073\037\032\040" +
    "\023\041\021\001\002\000\004\053\uffee\001\002\000\004" +
    "\021\074\001\002\000\004\053\uffd2\001\002\000\010\011" +
    "\053\023\054\053\076\001\002\000\026\005\005\016\011" +
    "\020\025\021\015\030\006\032\020\033\033\037\032\040" +
    "\023\041\021\001\002\000\004\053\100\001\002\000\030" +
    "\005\005\016\011\020\025\021\015\030\006\032\020\033" +
    "\033\036\101\037\032\040\023\041\021\001\002\000\004" +
    "\021\102\001\002\000\004\053\uffd1\001\002\000\006\014" +
    "\105\053\uffd9\001\002\000\012\011\053\014\uffd7\023\054" +
    "\053\uffd7\001\002\000\014\017\046\021\040\022\045\061" +
    "\042\062\047\001\002\000\012\011\053\014\uffd8\023\054" +
    "\053\uffd8\001\002\000\026\005\005\016\011\020\025\021" +
    "\015\030\006\032\020\033\033\037\032\040\023\041\021" +
    "\001\002\000\004\053\111\001\002\000\030\005\005\016" +
    "\011\020\025\021\015\024\112\030\006\032\020\033\033" +
    "\037\032\040\023\041\021\001\002\000\016\017\046\021" +
    "\040\022\045\044\116\061\042\062\047\001\002\000\022" +
    "\007\124\011\053\023\054\026\123\045\126\046\125\047" +
    "\120\054\122\001\002\000\010\042\131\043\132\053\uffd0" +
    "\001\002\000\012\013\uffc7\042\uffc7\043\uffc7\053\uffc7\001" +
    "\002\000\014\017\046\021\040\022\045\061\042\062\047" +
    "\001\002\000\022\007\124\011\053\023\054\026\123\045" +
    "\126\046\125\047\120\054\122\001\002\000\014\017\uffbd" +
    "\021\uffbd\022\uffbd\061\uffbd\062\uffbd\001\002\000\014\017" +
    "\046\021\040\022\045\061\042\062\047\001\002\000\014" +
    "\017\uffc1\021\uffc1\022\uffc1\061\uffc1\062\uffc1\001\002\000" +
    "\014\017\uffc2\021\uffc2\022\uffc2\061\uffc2\062\uffc2\001\002" +
    "\000\014\017\uffc0\021\uffc0\022\uffc0\061\uffc0\062\uffc0\001" +
    "\002\000\014\017\uffbe\021\uffbe\022\uffbe\061\uffbe\062\uffbe" +
    "\001\002\000\014\017\uffbf\021\uffbf\022\uffbf\061\uffbf\062" +
    "\uffbf\001\002\000\016\011\053\013\uffc4\023\054\042\uffc4" +
    "\043\uffc4\053\uffc4\001\002\000\016\017\046\021\040\022" +
    "\045\044\116\061\042\062\047\001\002\000\016\017\uffc6" +
    "\021\uffc6\022\uffc6\044\uffc6\061\uffc6\062\uffc6\001\002\000" +
    "\016\017\uffc5\021\uffc5\022\uffc5\044\uffc5\061\uffc5\062\uffc5" +
    "\001\002\000\012\013\uffc8\042\uffc8\043\uffc8\053\uffc8\001" +
    "\002\000\014\017\046\021\040\022\045\061\042\062\047" +
    "\001\002\000\016\011\053\013\uffc3\023\054\042\uffc3\043" +
    "\uffc3\053\uffc3\001\002\000\004\053\172\001\002\000\004" +
    "\053\140\001\002\000\030\005\005\015\141\016\011\020" +
    "\025\021\015\030\006\032\020\033\033\037\032\040\023" +
    "\041\021\001\002\000\006\002\ufffe\053\142\001\002\000" +
    "\006\002\ufffd\056\144\001\002\000\006\002\ufffa\053\170" +
    "\001\002\000\004\021\146\001\002\000\006\002\uffef\053" +
    "\uffef\001\002\000\004\017\147\001\002\000\012\012\150" +
    "\037\032\040\023\041\021\001\002\000\004\053\164\001" +
    "\002\000\004\021\163\001\002\000\006\012\154\060\153" +
    "\001\002\000\010\037\032\040\023\041\021\001\002\000" +
    "\004\053\155\001\002\000\026\005\005\016\011\020\025" +
    "\021\015\030\006\032\020\033\033\037\032\040\023\041" +
    "\021\001\002\000\004\053\157\001\002\000\030\005\005" +
    "\016\011\020\025\021\015\030\006\032\020\033\033\037" +
    "\032\040\023\041\021\057\160\001\002\000\006\002\uffcd" +
    "\053\uffcd\001\002\000\004\021\162\001\002\000\006\012" +
    "\uffcc\060\uffcc\001\002\000\006\012\uffcb\060\uffcb\001\002" +
    "\000\026\005\005\016\011\020\025\021\015\030\006\032" +
    "\020\033\033\037\032\040\023\041\021\001\002\000\004" +
    "\053\166\001\002\000\030\005\005\016\011\020\025\021" +
    "\015\030\006\032\020\033\033\037\032\040\023\041\021" +
    "\057\167\001\002\000\006\002\uffce\053\uffce\001\002\000" +
    "\006\002\ufff9\056\144\001\002\000\006\002\ufff0\053\ufff0" +
    "\001\002\000\006\002\ufff6\056\144\001\002\000\006\002" +
    "\ufff3\053\174\001\002\000\006\002\ufff2\056\144\001\002" +
    "\000\004\002\000\001\002\000\004\022\216\001\002\000" +
    "\006\012\203\021\202\001\002\000\014\017\046\021\040" +
    "\022\045\061\042\062\047\001\002\000\006\014\105\053" +
    "\uffdb\001\002\000\012\012\uffdc\051\213\053\uffdc\060\uffdc" +
    "\001\002\000\004\053\uffc9\001\002\000\006\012\206\060" +
    "\205\001\002\000\004\021\207\001\002\000\004\053\uffca" +
    "\001\002\000\012\012\uffdf\051\210\053\uffdf\060\uffdf\001" +
    "\002\000\004\022\211\001\002\000\004\052\212\001\002" +
    "\000\010\012\uffde\053\uffde\060\uffde\001\002\000\004\022" +
    "\214\001\002\000\004\052\215\001\002\000\010\012\uffdd" +
    "\053\uffdd\060\uffdd\001\002\000\004\052\217\001\002\000" +
    "\004\025\220\001\002\000\014\017\046\021\040\022\045" +
    "\061\042\062\047\001\002\000\006\014\105\053\uffda\001" +
    "\002\000\006\053\uffe3\060\205\001\002\000\030\005\005" +
    "\015\224\016\011\020\025\021\015\030\006\032\020\033" +
    "\033\037\032\040\023\041\021\001\002\000\006\002\001" +
    "\053\225\001\002\000\006\002\uffff\056\144\001\002\000" +
    "\006\002\ufffc\053\227\001\002\000\006\002\ufffb\056\144" +
    "\001\002\000\010\013\231\042\131\043\132\001\002\000" +
    "\004\053\232\001\002\000\026\005\005\016\011\020\025" +
    "\021\015\030\006\032\020\033\033\037\032\040\023\041" +
    "\021\001\002\000\004\053\234\001\002\000\032\005\005" +
    "\010\235\016\011\020\025\021\015\027\236\030\006\032" +
    "\020\033\033\037\032\040\023\041\021\001\002\000\004" +
    "\053\237\001\002\000\004\053\uffd4\001\002\000\026\005" +
    "\005\016\011\020\025\021\015\030\006\032\020\033\033" +
    "\037\032\040\023\041\021\001\002\000\004\053\241\001" +
    "\002\000\030\005\005\016\011\020\025\021\015\027\242" +
    "\030\006\032\020\033\033\037\032\040\023\041\021\001" +
    "\002\000\004\053\uffd3\001\002\000\006\002\ufff7\056\144" +
    "\001\002\000\006\002\ufff5\053\245\001\002\000\006\002" +
    "\ufff4\056\144\001\002\000\010\042\131\043\132\053\247" +
    "\001\002\000\026\005\005\016\011\020\025\021\015\030" +
    "\006\032\020\033\033\037\032\040\023\041\021\001\002" +
    "\000\004\053\251\001\002\000\030\005\005\016\011\020" +
    "\025\021\015\030\006\031\252\032\020\033\033\037\032" +
    "\040\023\041\021\001\002\000\004\053\uffcf\001\002\000" +
    "\004\053\uffd6\001\002\000\004\060\255\001\002\000\004" +
    "\021\256\001\002\000\004\053\uffd5\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\254\000\034\002\015\004\012\005\021\006\027\007" +
    "\013\011\003\012\023\014\034\015\026\016\033\017\030" +
    "\020\007\022\011\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\024\245\026\114\030\112\032\042\034\043" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\024" +
    "\227\026\114\030\112\032\042\034\043\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\221\001\001\000" +
    "\002\001\001\000\002\001\001\000\032\004\136\005\021" +
    "\006\027\007\013\011\003\012\023\014\034\015\026\016" +
    "\033\017\030\020\007\022\011\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\013\102\030\103\032\042\034\043" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\030\040\032\042\034\043\001\001\000\002\001\001" +
    "\000\004\031\051\001\001\000\002\001\001\000\004\033" +
    "\055\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\030\047\032\042\034\043\001\001\000\002\001\001\000" +
    "\004\031\051\001\001\000\002\001\001\000\006\032\054" +
    "\034\043\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\033\055\001\001\000\004\034\062\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\030\064\032\042\034\043" +
    "\001\001\000\004\031\051\001\001\000\010\030\074\032" +
    "\042\034\043\001\001\000\032\004\067\005\021\006\027" +
    "\007\013\011\003\012\023\014\034\015\026\016\033\017" +
    "\030\020\007\022\011\001\001\000\002\001\001\000\030" +
    "\005\071\006\027\007\013\011\003\012\023\014\034\015" +
    "\026\016\033\017\030\020\007\022\011\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\031" +
    "\051\001\001\000\032\004\076\005\021\006\027\007\013" +
    "\011\003\012\023\014\034\015\026\016\033\017\030\020" +
    "\007\022\011\001\001\000\002\001\001\000\030\005\071" +
    "\006\027\007\013\011\003\012\023\014\034\015\026\016" +
    "\033\017\030\020\007\022\011\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\031\051\001" +
    "\001\000\010\030\105\032\042\034\043\001\001\000\004" +
    "\031\051\001\001\000\032\004\107\005\021\006\027\007" +
    "\013\011\003\012\023\014\034\015\026\016\033\017\030" +
    "\020\007\022\011\001\001\000\002\001\001\000\030\005" +
    "\071\006\027\007\013\011\003\012\023\014\034\015\026" +
    "\016\033\017\030\020\007\022\011\001\001\000\014\024" +
    "\113\026\114\030\112\032\042\034\043\001\001\000\006" +
    "\027\133\031\051\001\001\000\004\025\127\001\001\000" +
    "\002\001\001\000\010\030\116\032\042\034\043\001\001" +
    "\000\006\027\120\031\051\001\001\000\002\001\001\000" +
    "\010\030\126\032\042\034\043\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\031\051\001\001\000\012\026\132" +
    "\030\112\032\042\034\043\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\030\134\032\042" +
    "\034\043\001\001\000\004\031\051\001\001\000\002\001" +
    "\001\000\002\001\001\000\030\005\071\006\027\007\013" +
    "\011\003\012\023\014\034\015\026\016\033\017\030\020" +
    "\007\022\011\001\001\000\002\001\001\000\006\003\142" +
    "\021\144\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\007\150\023\151" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\007\160\001\001\000\002\001\001\000\032" +
    "\004\155\005\021\006\027\007\013\011\003\012\023\014" +
    "\034\015\026\016\033\017\030\020\007\022\011\001\001" +
    "\000\002\001\001\000\030\005\071\006\027\007\013\011" +
    "\003\012\023\014\034\015\026\016\033\017\030\020\007" +
    "\022\011\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\032\004\164\005\021" +
    "\006\027\007\013\011\003\012\023\014\034\015\026\016" +
    "\033\017\030\020\007\022\011\001\001\000\002\001\001" +
    "\000\030\005\071\006\027\007\013\011\003\012\023\014" +
    "\034\015\026\016\033\017\030\020\007\022\011\001\001" +
    "\000\002\001\001\000\004\021\170\001\001\000\002\001" +
    "\001\000\006\003\172\021\144\001\001\000\002\001\001" +
    "\000\004\021\170\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\010\203\001\001\000\012\013\200\030\103" +
    "\032\042\034\043\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\013\220\030\103\032\042\034\043\001\001" +
    "\000\002\001\001\000\002\001\001\000\030\005\071\006" +
    "\027\007\013\011\003\012\023\014\034\015\026\016\033" +
    "\017\030\020\007\022\011\001\001\000\002\001\001\000" +
    "\006\003\225\021\144\001\001\000\002\001\001\000\004" +
    "\021\170\001\001\000\004\025\127\001\001\000\002\001" +
    "\001\000\032\004\232\005\021\006\027\007\013\011\003" +
    "\012\023\014\034\015\026\016\033\017\030\020\007\022" +
    "\011\001\001\000\002\001\001\000\030\005\071\006\027" +
    "\007\013\011\003\012\023\014\034\015\026\016\033\017" +
    "\030\020\007\022\011\001\001\000\002\001\001\000\002" +
    "\001\001\000\032\004\237\005\021\006\027\007\013\011" +
    "\003\012\023\014\034\015\026\016\033\017\030\020\007" +
    "\022\011\001\001\000\002\001\001\000\030\005\071\006" +
    "\027\007\013\011\003\012\023\014\034\015\026\016\033" +
    "\017\030\020\007\022\011\001\001\000\002\001\001\000" +
    "\006\003\243\021\144\001\001\000\002\001\001\000\004" +
    "\021\170\001\001\000\004\025\127\001\001\000\032\004" +
    "\247\005\021\006\027\007\013\011\003\012\023\014\034" +
    "\015\026\016\033\017\030\020\007\022\011\001\001\000" +
    "\002\001\001\000\030\005\071\006\027\007\013\011\003" +
    "\012\023\014\034\015\026\016\033\017\030\020\007\022" +
    "\011\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	
	public static void main(String args[]) throws Exception{
		parser sintactico;
	
		if(args.length>0){
			sintactico = new parser(new Scanner(new FileInputStream(args[0])));
			sintactico.parse();
		}else{
			System.out.println("No se encontró el código fuente (Parámetro incorrecto)");
		}
    
	}


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


	private Nodo arbol = new Nodo(TIPO.programa);

  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // factor ::= CADENA 
            {
              Nodo RESULT =null;
		int cadleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cadright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String cad = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								RESULT = new Constante(cad);
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // factor ::= ID 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								RESULT = new Identificador(id,-1,-1,null);
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // factor ::= NUM_FLOTANTE 
            {
              Nodo RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object num = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								RESULT = new Constante(num);
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // factor ::= NUM_ENTERO 
            {
              Nodo RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer num = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								RESULT = new Constante(num);
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // factor ::= LPAREN expresion_simple RPAREN 
            {
              Nodo RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Nodo exp = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
								RESULT = new Constante(exp);
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // op_mult ::= CIRCUMFLEX 
            {
              OP RESULT =null;
			RESULT = OP.POTENCIA; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // op_mult ::= MODULE 
            {
              OP RESULT =null;
			RESULT = OP.MODULO; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // op_mult ::= SLASH 
            {
              OP RESULT =null;
			RESULT = OP.DIVISION; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // op_mult ::= ASTERISK 
            {
              OP RESULT =null;
		 RESULT = OP.MULTIPLICACION; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // term ::= factor 
            {
              Nodo RESULT =null;
		int factorleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int factorright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo factor = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								RESULT = factor;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // term ::= term op_mult factor 
            {
              Nodo RESULT =null;
		int termleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int termright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo term = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int operandoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int operandoright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		OP operando = (OP)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int facleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int facright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo fac = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								Operacion tmp = new Operacion(operando);
								tmp.add(term);
								tmp.add(fac);
								
								RESULT = tmp;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // op_suma ::= MINUS 
            {
              OP RESULT =null;
		 RESULT = OP.RESTA; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_suma",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // op_suma ::= PLUS 
            {
              OP RESULT =null;
		 RESULT = OP.SUMA; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_suma",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expresion_simple ::= term 
            {
              Nodo RESULT =null;
		int termleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int termright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo term = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								RESULT = term;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_simple",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expresion_simple ::= expresion_simple op_suma term 
            {
              Nodo RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo exp = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int operandoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int operandoright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		OP operando = (OP)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int termleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int termright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo term = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								Operacion tmp = new Operacion(operando);
								tmp.add(exp);
								tmp.add(term);
								
								RESULT = tmp;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_simple",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // op_comparacion ::= GREATER_THAN_EQ 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // op_comparacion ::= GREATER_THAN 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // op_comparacion ::= LESS_THAN_EQ 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // op_comparacion ::= LESS_THAN 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // op_comparacion ::= DIFFERENT 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // op_comparacion ::= EQUAL 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expresion_comparacion ::= expresion_simple op_comparacion expresion_simple 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_comparacion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expresion_comparacion ::= NOT expresion_simple op_comparacion expresion_simple 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_comparacion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // op_logico ::= OR 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_logico",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // op_logico ::= AND 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_logico",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expresion_compuesta ::= expresion_comparacion 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_compuesta",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expresion_compuesta ::= expresion_compuesta op_logico expresion_comparacion 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_compuesta",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // call_proc ::= ID LPAREN RPAREN 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("call_proc",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // call_proc ::= ID LPAREN list_var RPAREN 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("call_proc",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // list_param ::= tipo_dato ID 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // list_param ::= list_param COMMA tipo_dato ID 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // def_proc ::= PROCEDURE ID LPAREN list_param RPAREN NEW_LINE secuencia_sent NEW_LINE ENDPROCEDURE 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("def_proc",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // def_proc ::= PROCEDURE ID LPAREN RPAREN NEW_LINE secuencia_sent NEW_LINE ENDPROCEDURE 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("def_proc",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // sent_while ::= WHILE expresion_compuesta NEW_LINE secuencia_sent NEW_LINE ENDWHILE 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_while",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // sent_do ::= DO NEW_LINE secuencia_sent NEW_LINE LOOP_UNTIL expresion_compuesta 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_do",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // sent_for ::= FOR ID ASSIGN expresion_simple TO expresion_simple STEP expresion_simple NEW_LINE secuencia_sent NEW_LINE NEXT ID 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_for",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-12)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // sent_for ::= FOR ID ASSIGN expresion_simple TO expresion_simple NEW_LINE secuencia_sent NEW_LINE NEXT ID 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_for",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // sent_if ::= IF expresion_compuesta THEN NEW_LINE secuencia_sent NEW_LINE ELSE NEW_LINE secuencia_sent NEW_LINE ENDIF 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_if",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // sent_if ::= IF expresion_compuesta THEN NEW_LINE secuencia_sent NEW_LINE ENDIF 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_if",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // sent_leer ::= INPUT CADENA COMMA ID 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_leer",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // sent_leer ::= INPUT ID 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_leer",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // list_impresion ::= expresion_simple 
            {
              Nodo RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo exp = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = exp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_impresion",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // list_impresion ::= list_impresion CONCAT expresion_simple 
            {
              Nodo RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo list = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int expleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo exp = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Nodo tmp = new Nodo(TIPO.list_impresion);
									tmp.add(list);
									tmp.add(exp);
									
									RESULT = tmp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_impresion",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // sent_escribir ::= PRINT list_impresion 
            {
              Nodo RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo list = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = new Escribir(list);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_escribir",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // sent_asignacion ::= ID LPOPPER NUM_ENTERO RPOPPER ASSIGN list_impresion 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int posleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int posright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Integer pos = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo list = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = new Asignacion(new Identificador(id,-1,pos,null),list);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_asignacion",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // sent_asignacion ::= ID ASSIGN list_impresion 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo list = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = new Asignacion(new Identificador(id,-1,-1,null),list);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_asignacion",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // list_var ::= ID 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
										
									RESULT = new Identificador(id,-1,-1,null);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_var",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // list_var ::= ID LPOPPER NUM_ENTERO RPOPPER 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int tamleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tamright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer tam = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
										
									RESULT = new Identificador(id,tam,-1,null);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_var",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // list_var ::= list_var COMMA ID LPOPPER NUM_ENTERO RPOPPER 
            {
              Nodo RESULT =null;
		int listvarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int listvarright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Nodo listvar = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int tamleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tamright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer tam = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
									Nodo tmp = new Nodo(TIPO.list_var);									
									tmp.add(listvar);
									tmp.add(new Identificador(id,tam,-1,null));
									
									RESULT = tmp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_var",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // list_var ::= list_var COMMA ID 
            {
              Nodo RESULT =null;
		int listvarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int listvarright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo listvar = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Nodo tmp = new Nodo(TIPO.list_var);									
									tmp.add(listvar);
									tmp.add(new Identificador(id,-1,-1,null));
									
									RESULT = tmp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_var",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // tipo_dato ::= STRING 
            {
              DATO RESULT =null;
			RESULT = DATO.STRING; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // tipo_dato ::= FLOAT 
            {
              DATO RESULT =null;
			RESULT = DATO.FLOAT; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // tipo_dato ::= INTEGER 
            {
              DATO RESULT =null;
			RESULT = DATO.INTEGER; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // sent_declaracion ::= tipo_dato list_var 
            {
              Nodo RESULT =null;
		int datoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int datoright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		DATO dato = (DATO)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int listvarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listvarright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo listvar = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								RESULT = new Declaracion(dato,listvar);
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_declaracion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sentencia ::= call_proc 
            {
              Nodo RESULT =null;
		int callprocleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int callprocright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo callproc = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = callproc;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sentencia ::= sent_while 
            {
              Nodo RESULT =null;
		int buclemientrasleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int buclemientrasright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo buclemientras = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = buclemientras;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // sentencia ::= sent_do 
            {
              Nodo RESULT =null;
		int buclehagaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int buclehagaright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo buclehaga = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = buclehaga;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // sentencia ::= sent_for 
            {
              Nodo RESULT =null;
		int bucleparaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int buclepararight = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo buclepara = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = buclepara;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // sentencia ::= sent_if 
            {
              Nodo RESULT =null;
		int decisionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int decisionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo decision = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = decision;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // sentencia ::= sent_leer 
            {
              Nodo RESULT =null;
		int leerleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int leerright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo leer = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = leer;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // sentencia ::= sent_escribir 
            {
              Nodo RESULT =null;
		int escribirleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int escribirright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo escribir = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = escribir;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // sentencia ::= sent_asignacion 
            {
              Nodo RESULT =null;
		int asignacionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int asignacionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo asignacion = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = asignacion;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // sentencia ::= sent_declaracion 
            {
              Nodo RESULT =null;
		int declaracionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int declaracionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo declaracion = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = declaracion;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // secuencia_sent ::= sentencia 
            {
              Nodo RESULT =null;
		int sentleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sentright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo sent = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Nodo tmp = new Nodo(TIPO.secuencia_sent);									
									tmp.add(sent);
									RESULT = tmp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("secuencia_sent",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // secuencia_sent ::= secuencia_sent NEW_LINE sentencia 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sentleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sentright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo sent = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Nodo tmp = new Nodo(TIPO.secuencia_sent);
									tmp.add(secuencia);
									tmp.add(sent);

									RESULT = tmp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("secuencia_sent",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // sub_programa ::= def_proc 
            {
              Nodo RESULT =null;
		int procleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int procright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo proc = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Nodo tmp = new Nodo(TIPO.sub_programa);
									tmp.add(proc);
									RESULT = tmp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sub_programa",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sub_programa ::= sub_programa NEW_LINE def_proc 
            {
              Nodo RESULT =null;
		int subleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int subright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo sub = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int procleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int procright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo proc = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Nodo tmp = new Nodo(TIPO.sub_programa);
									tmp.add(sub);
									tmp.add(proc);
									
									RESULT = tmp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sub_programa",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // programa ::= error 
            {
              Nodo RESULT =null;
			System.out.println("Error sintáctico!"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // programa ::= NEW_LINE END NEW_LINE sub_programa NEW_LINE 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // programa ::= NEW_LINE END NEW_LINE sub_programa 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // programa ::= END NEW_LINE sub_programa NEW_LINE 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // programa ::= END NEW_LINE sub_programa 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // programa ::= NEW_LINE END NEW_LINE 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // programa ::= END NEW_LINE 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // programa ::= END 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // programa ::= NEW_LINE secuencia_sent NEW_LINE END NEW_LINE sub_programa NEW_LINE 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int subleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int subright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Nodo sub = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
			
									arbol.add(secuencia);
									arbol.add(sub);								
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // programa ::= NEW_LINE secuencia_sent NEW_LINE END NEW_LINE sub_programa 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int subleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int subright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo sub = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			
									arbol.add(secuencia);
									arbol.add(sub);								
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // programa ::= secuencia_sent NEW_LINE END NEW_LINE sub_programa NEW_LINE 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int subleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int subright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Nodo sub = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
									arbol.add(secuencia);
									arbol.add(sub);								
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // programa ::= secuencia_sent NEW_LINE END NEW_LINE sub_programa 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int subleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int subright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo sub = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			
									arbol.add(secuencia);
									arbol.add(sub);								
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // programa ::= NEW_LINE secuencia_sent NEW_LINE END NEW_LINE 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		
									arbol.add(secuencia);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // programa ::= NEW_LINE secuencia_sent NEW_LINE END 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
									arbol.add(secuencia);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= secuencia_sent NEW_LINE END NEW_LINE 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		
									arbol.add(secuencia);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Nodo start_val = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // programa ::= secuencia_sent NEW_LINE END 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
									arbol.add(secuencia);
									arbol.printTree();
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

