
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 07 02:45:26 VET 2011
//----------------------------------------------------

package sintactico;

import arbol.*;
import arbol.Nodo.TIPO;
import arbol.Variable.DATO;
import arbol.Operacion.OP;
import arbol.Comparacion.OP_COMPARACION;
import arbol.Comparacion.OP_LOGICO;
import lexico.Scanner;
import java_cup.runtime.*;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStreamReader;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Nov 07 02:45:26 VET 2011
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\127\000\002\002\005\000\002\002\004\000\002\002" +
    "\006\000\002\002\006\000\002\002\007\000\002\002\007" +
    "\000\002\002\010\000\002\002\010\000\002\002\011\000" +
    "\002\002\003\000\002\002\004\000\002\002\005\000\002" +
    "\002\005\000\002\002\006\000\002\002\006\000\002\002" +
    "\007\000\002\002\003\000\002\003\005\000\002\003\003" +
    "\000\002\004\005\000\002\004\003\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\005\003\000\002\005\003\000\002\005" +
    "\003\000\002\005\003\000\002\006\004\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\010\005\000" +
    "\002\010\010\000\002\010\006\000\002\010\003\000\002" +
    "\011\005\000\002\011\010\000\002\012\004\000\002\013" +
    "\005\000\002\013\003\000\002\014\004\000\002\014\007" +
    "\000\002\014\006\000\002\014\011\000\002\015\011\000" +
    "\002\015\015\000\002\016\015\000\002\016\017\000\002" +
    "\017\010\000\002\020\010\000\002\021\012\000\002\021" +
    "\013\000\002\023\006\000\002\023\004\000\002\022\006" +
    "\000\002\022\005\000\002\024\005\000\002\024\003\000" +
    "\002\025\003\000\002\025\003\000\002\026\006\000\002" +
    "\026\005\000\002\027\003\000\002\027\003\000\002\027" +
    "\003\000\002\027\003\000\002\027\003\000\002\027\003" +
    "\000\002\030\005\000\002\030\003\000\002\031\003\000" +
    "\002\031\003\000\002\032\005\000\002\032\003\000\002" +
    "\033\003\000\002\033\003\000\002\033\003\000\002\033" +
    "\003\000\002\034\005\000\002\034\003\000\002\034\003" +
    "\000\002\034\003\000\002\034\006\000\002\034\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\265\000\034\003\026\005\005\015\007\016\011\020" +
    "\025\021\015\030\006\032\020\033\033\037\032\040\023" +
    "\041\021\053\017\001\002\000\004\053\uffeb\001\002\000" +
    "\006\021\256\062\257\001\002\000\016\017\046\021\040" +
    "\022\044\044\120\061\045\062\047\001\002\000\006\002" +
    "\ufff8\053\246\001\002\000\004\053\uffe5\001\002\000\016" +
    "\017\046\021\040\022\044\044\120\061\045\062\047\001" +
    "\002\000\004\053\uffe4\001\002\000\004\053\226\001\002" +
    "\000\004\021\205\001\002\000\010\017\202\025\203\051" +
    "\201\001\002\000\004\002\200\001\002\000\030\005\005" +
    "\015\141\016\011\020\025\021\015\030\006\032\020\033" +
    "\033\037\032\040\023\041\021\001\002\000\004\053\112" +
    "\001\002\000\004\021\uffe0\001\002\000\004\053\uffed\001" +
    "\002\000\004\021\uffe1\001\002\000\004\053\uffea\001\002" +
    "\000\014\017\046\021\040\022\044\061\045\062\047\001" +
    "\002\000\004\002\ufff1\001\002\000\004\053\uffe8\001\002" +
    "\000\004\053\uffec\001\002\000\004\053\uffe6\001\002\000" +
    "\004\021\uffe2\001\002\000\004\021\036\001\002\000\004" +
    "\053\uffe7\001\002\000\004\053\uffe9\001\002\000\004\025" +
    "\037\001\002\000\014\017\046\021\040\022\044\061\045" +
    "\062\047\001\002\000\054\004\uffad\006\uffad\007\uffad\011" +
    "\uffad\012\uffad\013\uffad\014\uffad\023\uffad\026\uffad\034\uffad" +
    "\035\uffad\042\uffad\043\uffad\045\uffad\046\uffad\047\uffad\050" +
    "\uffad\051\103\053\uffad\054\uffad\055\uffad\001\002\000\010" +
    "\011\052\023\054\034\064\001\002\000\052\004\061\006" +
    "\060\007\uffb9\011\uffb9\012\uffb9\013\uffb9\014\uffb9\023\uffb9" +
    "\026\uffb9\034\uffb9\035\uffb9\042\uffb9\043\uffb9\045\uffb9\046" +
    "\uffb9\047\uffb9\050\062\053\uffb9\054\uffb9\055\057\001\002" +
    "\000\052\004\uffb5\006\uffb5\007\uffb5\011\uffb5\012\uffb5\013" +
    "\uffb5\014\uffb5\023\uffb5\026\uffb5\034\uffb5\035\uffb5\042\uffb5" +
    "\043\uffb5\045\uffb5\046\uffb5\047\uffb5\050\uffb5\053\uffb5\054" +
    "\uffb5\055\uffb5\001\002\000\052\004\uffaf\006\uffaf\007\uffaf" +
    "\011\uffaf\012\uffaf\013\uffaf\014\uffaf\023\uffaf\026\uffaf\034" +
    "\uffaf\035\uffaf\042\uffaf\043\uffaf\045\uffaf\046\uffaf\047\uffaf" +
    "\050\uffaf\053\uffaf\054\uffaf\055\uffaf\001\002\000\052\004" +
    "\uffae\006\uffae\007\uffae\011\uffae\012\uffae\013\uffae\014\uffae" +
    "\023\uffae\026\uffae\034\uffae\035\uffae\042\uffae\043\uffae\045" +
    "\uffae\046\uffae\047\uffae\050\uffae\053\uffae\054\uffae\055\uffae" +
    "\001\002\000\014\017\046\021\040\022\044\061\045\062" +
    "\047\001\002\000\052\004\uffab\006\uffab\007\uffab\011\uffab" +
    "\012\uffab\013\uffab\014\uffab\023\uffab\026\uffab\034\uffab\035" +
    "\uffab\042\uffab\043\uffab\045\uffab\046\uffab\047\uffab\050\uffab" +
    "\053\uffab\054\uffab\055\uffab\001\002\000\010\011\052\012" +
    "\051\023\054\001\002\000\052\004\uffb0\006\uffb0\007\uffb0" +
    "\011\uffb0\012\uffb0\013\uffb0\014\uffb0\023\uffb0\026\uffb0\034" +
    "\uffb0\035\uffb0\042\uffb0\043\uffb0\045\uffb0\046\uffb0\047\uffb0" +
    "\050\uffb0\053\uffb0\054\uffb0\055\uffb0\001\002\000\014\017" +
    "\uffb8\021\uffb8\022\uffb8\061\uffb8\062\uffb8\001\002\000\014" +
    "\017\046\021\040\022\044\061\045\062\047\001\002\000" +
    "\014\017\uffb7\021\uffb7\022\uffb7\061\uffb7\062\uffb7\001\002" +
    "\000\052\004\061\006\060\007\uffba\011\uffba\012\uffba\013" +
    "\uffba\014\uffba\023\uffba\026\uffba\034\uffba\035\uffba\042\uffba" +
    "\043\uffba\045\uffba\046\uffba\047\uffba\050\062\053\uffba\054" +
    "\uffba\055\057\001\002\000\014\017\046\021\040\022\044" +
    "\061\045\062\047\001\002\000\014\017\uffb2\021\uffb2\022" +
    "\uffb2\061\uffb2\062\uffb2\001\002\000\014\017\uffb3\021\uffb3" +
    "\022\uffb3\061\uffb3\062\uffb3\001\002\000\014\017\uffb4\021" +
    "\uffb4\022\uffb4\061\uffb4\062\uffb4\001\002\000\014\017\uffb1" +
    "\021\uffb1\022\uffb1\061\uffb1\062\uffb1\001\002\000\052\004" +
    "\uffb6\006\uffb6\007\uffb6\011\uffb6\012\uffb6\013\uffb6\014\uffb6" +
    "\023\uffb6\026\uffb6\034\uffb6\035\uffb6\042\uffb6\043\uffb6\045" +
    "\uffb6\046\uffb6\047\uffb6\050\uffb6\053\uffb6\054\uffb6\055\uffb6" +
    "\001\002\000\014\017\046\021\040\022\044\061\045\062" +
    "\047\001\002\000\012\011\052\023\054\035\066\053\067" +
    "\001\002\000\014\017\046\021\040\022\044\061\045\062" +
    "\047\001\002\000\026\005\005\016\011\020\025\021\015" +
    "\030\006\032\020\033\033\037\032\040\023\041\021\001" +
    "\002\000\004\053\071\001\002\000\030\005\005\016\011" +
    "\020\025\021\015\030\006\032\020\033\033\036\073\037" +
    "\032\040\023\041\021\001\002\000\004\053\uffee\001\002" +
    "\000\004\021\074\001\002\000\004\053\uffd0\001\002\000" +
    "\010\011\052\023\054\053\076\001\002\000\026\005\005" +
    "\016\011\020\025\021\015\030\006\032\020\033\033\037" +
    "\032\040\023\041\021\001\002\000\004\053\100\001\002" +
    "\000\030\005\005\016\011\020\025\021\015\030\006\032" +
    "\020\033\033\036\101\037\032\040\023\041\021\001\002" +
    "\000\004\021\102\001\002\000\004\053\uffcf\001\002\000" +
    "\004\022\104\001\002\000\004\052\105\001\002\000\052" +
    "\004\uffac\006\uffac\007\uffac\011\uffac\012\uffac\013\uffac\014" +
    "\uffac\023\uffac\026\uffac\034\uffac\035\uffac\042\uffac\043\uffac" +
    "\045\uffac\046\uffac\047\uffac\050\uffac\053\uffac\054\uffac\055" +
    "\uffac\001\002\000\006\014\110\053\uffd9\001\002\000\012" +
    "\011\052\014\uffd7\023\054\053\uffd7\001\002\000\014\017" +
    "\046\021\040\022\044\061\045\062\047\001\002\000\012" +
    "\011\052\014\uffd8\023\054\053\uffd8\001\002\000\026\005" +
    "\005\016\011\020\025\021\015\030\006\032\020\033\033" +
    "\037\032\040\023\041\021\001\002\000\004\053\114\001" +
    "\002\000\030\005\005\016\011\020\025\021\015\024\115" +
    "\030\006\032\020\033\033\037\032\040\023\041\021\001" +
    "\002\000\016\017\046\021\040\022\044\044\120\061\045" +
    "\062\047\001\002\000\022\007\127\011\052\023\054\026" +
    "\126\045\131\046\130\047\123\054\125\001\002\000\010" +
    "\042\134\043\135\053\uffce\001\002\000\014\017\046\021" +
    "\040\022\044\061\045\062\047\001\002\000\012\013\uffc5" +
    "\042\uffc5\043\uffc5\053\uffc5\001\002\000\022\007\127\011" +
    "\052\023\054\026\126\045\131\046\130\047\123\054\125" +
    "\001\002\000\014\017\uffbb\021\uffbb\022\uffbb\061\uffbb\062" +
    "\uffbb\001\002\000\014\017\046\021\040\022\044\061\045" +
    "\062\047\001\002\000\014\017\uffbf\021\uffbf\022\uffbf\061" +
    "\uffbf\062\uffbf\001\002\000\014\017\uffc0\021\uffc0\022\uffc0" +
    "\061\uffc0\062\uffc0\001\002\000\014\017\uffbe\021\uffbe\022" +
    "\uffbe\061\uffbe\062\uffbe\001\002\000\014\017\uffbc\021\uffbc" +
    "\022\uffbc\061\uffbc\062\uffbc\001\002\000\014\017\uffbd\021" +
    "\uffbd\022\uffbd\061\uffbd\062\uffbd\001\002\000\016\011\052" +
    "\013\uffc2\023\054\042\uffc2\043\uffc2\053\uffc2\001\002\000" +
    "\016\017\046\021\040\022\044\044\120\061\045\062\047" +
    "\001\002\000\016\017\uffc4\021\uffc4\022\uffc4\044\uffc4\061" +
    "\uffc4\062\uffc4\001\002\000\016\017\uffc3\021\uffc3\022\uffc3" +
    "\044\uffc3\061\uffc3\062\uffc3\001\002\000\012\013\uffc6\042" +
    "\uffc6\043\uffc6\053\uffc6\001\002\000\014\017\046\021\040" +
    "\022\044\061\045\062\047\001\002\000\016\011\052\013" +
    "\uffc1\023\054\042\uffc1\043\uffc1\053\uffc1\001\002\000\004" +
    "\053\175\001\002\000\004\053\143\001\002\000\030\005" +
    "\005\015\144\016\011\020\025\021\015\030\006\032\020" +
    "\033\033\037\032\040\023\041\021\001\002\000\006\002" +
    "\ufffe\053\145\001\002\000\006\002\ufffd\056\147\001\002" +
    "\000\006\002\ufffa\053\173\001\002\000\004\021\151\001" +
    "\002\000\006\002\uffef\053\uffef\001\002\000\004\017\152" +
    "\001\002\000\012\012\153\037\032\040\023\041\021\001" +
    "\002\000\004\053\167\001\002\000\004\021\166\001\002" +
    "\000\006\012\157\060\156\001\002\000\010\037\032\040" +
    "\023\041\021\001\002\000\004\053\160\001\002\000\026" +
    "\005\005\016\011\020\025\021\015\030\006\032\020\033" +
    "\033\037\032\040\023\041\021\001\002\000\004\053\162" +
    "\001\002\000\030\005\005\016\011\020\025\021\015\030" +
    "\006\032\020\033\033\037\032\040\023\041\021\057\163" +
    "\001\002\000\006\002\uffcb\053\uffcb\001\002\000\004\021" +
    "\165\001\002\000\006\012\uffca\060\uffca\001\002\000\006" +
    "\012\uffc9\060\uffc9\001\002\000\026\005\005\016\011\020" +
    "\025\021\015\030\006\032\020\033\033\037\032\040\023" +
    "\041\021\001\002\000\004\053\171\001\002\000\030\005" +
    "\005\016\011\020\025\021\015\030\006\032\020\033\033" +
    "\037\032\040\023\041\021\057\172\001\002\000\006\002" +
    "\uffcc\053\uffcc\001\002\000\006\002\ufff9\056\147\001\002" +
    "\000\006\002\ufff0\053\ufff0\001\002\000\006\002\ufff6\056" +
    "\147\001\002\000\006\002\ufff3\053\177\001\002\000\006" +
    "\002\ufff2\056\147\001\002\000\004\002\000\001\002\000" +
    "\004\022\221\001\002\000\006\012\206\021\205\001\002" +
    "\000\014\017\046\021\040\022\044\061\045\062\047\001" +
    "\002\000\010\011\052\023\054\053\uffdb\001\002\000\012" +
    "\012\uffdc\051\216\053\uffdc\060\uffdc\001\002\000\004\053" +
    "\uffc7\001\002\000\006\012\211\060\210\001\002\000\004" +
    "\021\212\001\002\000\004\053\uffc8\001\002\000\012\012" +
    "\uffdf\051\213\053\uffdf\060\uffdf\001\002\000\004\022\214" +
    "\001\002\000\004\052\215\001\002\000\010\012\uffde\053" +
    "\uffde\060\uffde\001\002\000\004\022\217\001\002\000\004" +
    "\052\220\001\002\000\010\012\uffdd\053\uffdd\060\uffdd\001" +
    "\002\000\004\052\222\001\002\000\004\025\223\001\002" +
    "\000\014\017\046\021\040\022\044\061\045\062\047\001" +
    "\002\000\010\011\052\023\054\053\uffda\001\002\000\006" +
    "\053\uffe3\060\210\001\002\000\030\005\005\015\227\016" +
    "\011\020\025\021\015\030\006\032\020\033\033\037\032" +
    "\040\023\041\021\001\002\000\006\002\001\053\230\001" +
    "\002\000\006\002\uffff\056\147\001\002\000\006\002\ufffc" +
    "\053\232\001\002\000\006\002\ufffb\056\147\001\002\000" +
    "\010\013\234\042\134\043\135\001\002\000\004\053\235" +
    "\001\002\000\026\005\005\016\011\020\025\021\015\030" +
    "\006\032\020\033\033\037\032\040\023\041\021\001\002" +
    "\000\004\053\237\001\002\000\032\005\005\010\240\016" +
    "\011\020\025\021\015\027\241\030\006\032\020\033\033" +
    "\037\032\040\023\041\021\001\002\000\004\053\242\001" +
    "\002\000\004\053\uffd2\001\002\000\026\005\005\016\011" +
    "\020\025\021\015\030\006\032\020\033\033\037\032\040" +
    "\023\041\021\001\002\000\004\053\244\001\002\000\030" +
    "\005\005\016\011\020\025\021\015\027\245\030\006\032" +
    "\020\033\033\037\032\040\023\041\021\001\002\000\004" +
    "\053\uffd1\001\002\000\006\002\ufff7\056\147\001\002\000" +
    "\006\002\ufff5\053\250\001\002\000\006\002\ufff4\056\147" +
    "\001\002\000\010\042\134\043\135\053\252\001\002\000" +
    "\026\005\005\016\011\020\025\021\015\030\006\032\020" +
    "\033\033\037\032\040\023\041\021\001\002\000\004\053" +
    "\254\001\002\000\030\005\005\016\011\020\025\021\015" +
    "\030\006\031\255\032\020\033\033\037\032\040\023\041" +
    "\021\001\002\000\004\053\uffcd\001\002\000\006\051\265" +
    "\053\uffd6\001\002\000\004\060\260\001\002\000\004\021" +
    "\261\001\002\000\006\051\262\053\uffd4\001\002\000\004" +
    "\022\263\001\002\000\004\052\264\001\002\000\004\053" +
    "\uffd3\001\002\000\004\022\266\001\002\000\004\052\267" +
    "\001\002\000\004\053\uffd5\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\265\000\034\002\015\004\012\005\021\006\027\007" +
    "\013\011\003\012\023\014\034\015\026\016\033\017\030" +
    "\020\007\022\011\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\024\250\026\120\030\115\032\041\034\042" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\024" +
    "\232\026\120\030\115\032\041\034\042\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\224\001\001\000" +
    "\002\001\001\000\002\001\001\000\032\004\141\005\021" +
    "\006\027\007\013\011\003\012\023\014\034\015\026\016" +
    "\033\017\030\020\007\022\011\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\013\105\030\106\032\041\034\042" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\030\040\032\041\034\042\001\001\000\002\001\001" +
    "\000\004\031\052\001\001\000\004\033\055\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\030\047\032\041\034\042\001\001\000\002\001\001\000" +
    "\004\031\052\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\032\054\034\042\001\001\000\002\001\001\000" +
    "\004\033\055\001\001\000\004\034\062\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\030\064\032\041\034\042" +
    "\001\001\000\004\031\052\001\001\000\010\030\074\032" +
    "\041\034\042\001\001\000\032\004\067\005\021\006\027" +
    "\007\013\011\003\012\023\014\034\015\026\016\033\017" +
    "\030\020\007\022\011\001\001\000\002\001\001\000\030" +
    "\005\071\006\027\007\013\011\003\012\023\014\034\015" +
    "\026\016\033\017\030\020\007\022\011\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\031" +
    "\052\001\001\000\032\004\076\005\021\006\027\007\013" +
    "\011\003\012\023\014\034\015\026\016\033\017\030\020" +
    "\007\022\011\001\001\000\002\001\001\000\030\005\071" +
    "\006\027\007\013\011\003\012\023\014\034\015\026\016" +
    "\033\017\030\020\007\022\011\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\031\052\001\001" +
    "\000\010\030\110\032\041\034\042\001\001\000\004\031" +
    "\052\001\001\000\032\004\112\005\021\006\027\007\013" +
    "\011\003\012\023\014\034\015\026\016\033\017\030\020" +
    "\007\022\011\001\001\000\002\001\001\000\030\005\071" +
    "\006\027\007\013\011\003\012\023\014\034\015\026\016" +
    "\033\017\030\020\007\022\011\001\001\000\014\024\116" +
    "\026\120\030\115\032\041\034\042\001\001\000\006\027" +
    "\136\031\052\001\001\000\004\025\132\001\001\000\010" +
    "\030\121\032\041\034\042\001\001\000\002\001\001\000" +
    "\006\027\123\031\052\001\001\000\002\001\001\000\010" +
    "\030\131\032\041\034\042\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\031\052\001\001\000\012\026\135\030" +
    "\115\032\041\034\042\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\030\137\032\041\034" +
    "\042\001\001\000\004\031\052\001\001\000\002\001\001" +
    "\000\002\001\001\000\030\005\071\006\027\007\013\011" +
    "\003\012\023\014\034\015\026\016\033\017\030\020\007" +
    "\022\011\001\001\000\002\001\001\000\006\003\145\021" +
    "\147\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\007\153\023\154\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\007\163\001\001\000\002\001\001\000\032\004" +
    "\160\005\021\006\027\007\013\011\003\012\023\014\034" +
    "\015\026\016\033\017\030\020\007\022\011\001\001\000" +
    "\002\001\001\000\030\005\071\006\027\007\013\011\003" +
    "\012\023\014\034\015\026\016\033\017\030\020\007\022" +
    "\011\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\032\004\167\005\021\006" +
    "\027\007\013\011\003\012\023\014\034\015\026\016\033" +
    "\017\030\020\007\022\011\001\001\000\002\001\001\000" +
    "\030\005\071\006\027\007\013\011\003\012\023\014\034" +
    "\015\026\016\033\017\030\020\007\022\011\001\001\000" +
    "\002\001\001\000\004\021\173\001\001\000\002\001\001" +
    "\000\006\003\175\021\147\001\001\000\002\001\001\000" +
    "\004\021\173\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\010\206\001\001\000\010\030\203\032\041\034" +
    "\042\001\001\000\004\031\052\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\030\223\032\041\034\042\001\001\000\004\031" +
    "\052\001\001\000\002\001\001\000\030\005\071\006\027" +
    "\007\013\011\003\012\023\014\034\015\026\016\033\017" +
    "\030\020\007\022\011\001\001\000\002\001\001\000\006" +
    "\003\230\021\147\001\001\000\002\001\001\000\004\021" +
    "\173\001\001\000\004\025\132\001\001\000\002\001\001" +
    "\000\032\004\235\005\021\006\027\007\013\011\003\012" +
    "\023\014\034\015\026\016\033\017\030\020\007\022\011" +
    "\001\001\000\002\001\001\000\030\005\071\006\027\007" +
    "\013\011\003\012\023\014\034\015\026\016\033\017\030" +
    "\020\007\022\011\001\001\000\002\001\001\000\002\001" +
    "\001\000\032\004\242\005\021\006\027\007\013\011\003" +
    "\012\023\014\034\015\026\016\033\017\030\020\007\022" +
    "\011\001\001\000\002\001\001\000\030\005\071\006\027" +
    "\007\013\011\003\012\023\014\034\015\026\016\033\017" +
    "\030\020\007\022\011\001\001\000\002\001\001\000\006" +
    "\003\246\021\147\001\001\000\002\001\001\000\004\021" +
    "\173\001\001\000\004\025\132\001\001\000\032\004\252" +
    "\005\021\006\027\007\013\011\003\012\023\014\034\015" +
    "\026\016\033\017\030\020\007\022\011\001\001\000\002" +
    "\001\001\000\030\005\071\006\027\007\013\011\003\012" +
    "\023\014\034\015\026\016\033\017\030\020\007\022\011" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	
	public static void main(String args[]) throws Exception{
		parser sintactico;
	
		if(args.length>0){
			sintactico = new parser(new Scanner(new FileInputStream(args[0])));
			sintactico.parse();
		}else{
			System.out.println("No se encontró el código fuente (Parámetro incorrecto)");
		}
    
	}


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


	private Nodo arbol = new Nodo(TIPO._PROGRAMA_);
	
	private Symbols tabla_simbolos = new Symbols();
	private InputStreamReader entrada = new InputStreamReader(System.in);
    private BufferedReader buf = new BufferedReader (entrada);

  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // factor ::= CADENA 
            {
              Nodo RESULT =null;
		int cadleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cadright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String cad = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								RESULT = new Constante(cad);
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // factor ::= ID LPOPPER NUM_ENTERO RPOPPER 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int posleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int posright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer pos = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
										
								RESULT = new Constante(tabla_simbolos.getValorAt(id,pos));
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // factor ::= ID 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
										
								RESULT = new Constante(tabla_simbolos.getValorAt(id));
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // factor ::= NUM_FLOTANTE 
            {
              Nodo RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object num = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								RESULT = new Constante(num);
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // factor ::= NUM_ENTERO 
            {
              Nodo RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer num = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								RESULT = new Constante(num);
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // factor ::= LPAREN expresion_simple RPAREN 
            {
              Nodo RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Nodo exp = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
								RESULT = exp;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // op_mult ::= CIRCUMFLEX 
            {
              OP RESULT =null;
			RESULT = OP.POTENCIA; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // op_mult ::= MODULE 
            {
              OP RESULT =null;
			RESULT = OP.MODULO; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // op_mult ::= SLASH 
            {
              OP RESULT =null;
			RESULT = OP.DIVISION; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // op_mult ::= ASTERISK 
            {
              OP RESULT =null;
		 RESULT = OP.MULTIPLICACION; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_mult",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // term ::= factor 
            {
              Nodo RESULT =null;
		int factorleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int factorright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo factor = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								RESULT = factor;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // term ::= term op_mult factor 
            {
              Nodo RESULT =null;
		int termleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int termright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo term = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int operandoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int operandoright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		OP operando = (OP)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int facleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int facright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo fac = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								Operacion tmp = new Operacion(operando);
								
								if(term.getTipo()==TIPO.CONSTANTE && ((Constante)term).getTipodato()==String.class
									|| fac.getTipo()==TIPO.CONSTANTE && ((Constante)fac).getTipodato()==String.class)									
										System.out.println("Error! - No se pueden realizar operaciones aritméticas con cadenas");
									else{
										tmp.add(term);
										tmp.add(fac);
										tmp.calcular();
										
										RESULT = tmp;
									}													
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // op_suma ::= MINUS 
            {
              OP RESULT =null;
		 RESULT = OP.RESTA; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_suma",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // op_suma ::= PLUS 
            {
              OP RESULT =null;
		 RESULT = OP.SUMA; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_suma",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expresion_simple ::= term 
            {
              Nodo RESULT =null;
		int termleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int termright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo term = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								RESULT = term;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_simple",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expresion_simple ::= expresion_simple op_suma term 
            {
              Nodo RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo exp = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int operandoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int operandoright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		OP operando = (OP)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int termleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int termright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo term = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								Operacion tmp = new Operacion(operando);
								
								if(exp.getTipo()==TIPO.CONSTANTE && ((Constante)exp).getTipodato()==String.class
									|| term.getTipo()==TIPO.CONSTANTE && ((Constante)term).getTipodato()==String.class)									
										System.out.println("Error! - No se pueden realizar operaciones aritméticas con cadenas");
									else{
										tmp.add(exp);
										tmp.add(term);
										tmp.calcular();
										
										RESULT = tmp;
									}															
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_simple",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // op_comparacion ::= GREATER_THAN_EQ 
            {
              OP_COMPARACION RESULT =null;
		 RESULT = OP_COMPARACION.MAYOR_IGUAL_A; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // op_comparacion ::= GREATER_THAN 
            {
              OP_COMPARACION RESULT =null;
		 RESULT = OP_COMPARACION.MAYOR_A; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // op_comparacion ::= LESS_THAN_EQ 
            {
              OP_COMPARACION RESULT =null;
		 RESULT = OP_COMPARACION.MENOR_IGUAL_A; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // op_comparacion ::= LESS_THAN 
            {
              OP_COMPARACION RESULT =null;
		 RESULT = OP_COMPARACION.MENOR_A; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // op_comparacion ::= DIFFERENT 
            {
              OP_COMPARACION RESULT =null;
		 RESULT = OP_COMPARACION.DIFERENTE_A; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // op_comparacion ::= EQUAL 
            {
              OP_COMPARACION RESULT =null;
		 RESULT = OP_COMPARACION.IGUAL_A; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_comparacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expresion_comparacion ::= expresion_simple op_comparacion expresion_simple 
            {
              Nodo RESULT =null;
		int exp1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exp1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo exp1 = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		OP_COMPARACION op = (OP_COMPARACION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int exp2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exp2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo exp2 = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Comparacion tmp = new Comparacion(op);
									tmp.add(exp1);
									tmp.add(exp2);
									tmp.calcular(op);									
									
									RESULT = tmp;								
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_comparacion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expresion_comparacion ::= NOT expresion_simple op_comparacion expresion_simple 
            {
              Nodo RESULT =null;
		int exp1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exp1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo exp1 = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		OP_COMPARACION op = (OP_COMPARACION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int exp2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exp2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo exp2 = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Comparacion tmp = new Comparacion(op);
									tmp.add(exp1);
									tmp.add(exp2);
									tmp.calcular(op);
									tmp.setNot();
									
									RESULT = tmp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_comparacion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // op_logico ::= OR 
            {
              OP_LOGICO RESULT =null;
		 RESULT = OP_LOGICO.O; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_logico",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // op_logico ::= AND 
            {
              OP_LOGICO RESULT =null;
		 RESULT = OP_LOGICO.Y; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_logico",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresion_compuesta ::= expresion_comparacion 
            {
              Nodo RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo exp = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								RESULT = exp;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_compuesta",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresion_compuesta ::= expresion_compuesta op_logico expresion_comparacion 
            {
              Nodo RESULT =null;
		int exp1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exp1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo exp1 = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		OP_LOGICO op = (OP_LOGICO)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int exp2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exp2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo exp2 = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Comparacion tmp = new Comparacion(op);
									tmp.add(exp1);
									tmp.add(exp2);
									tmp.calcular(op);
									
									RESULT = tmp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_compuesta",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // call_proc ::= ID LPAREN RPAREN 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("call_proc",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // call_proc ::= ID LPAREN list_var RPAREN 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("call_proc",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // list_param ::= tipo_dato ID 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // list_param ::= list_param COMMA tipo_dato ID 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // def_proc ::= PROCEDURE ID LPAREN list_param RPAREN NEW_LINE secuencia_sent NEW_LINE ENDPROCEDURE 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("def_proc",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // def_proc ::= PROCEDURE ID LPAREN RPAREN NEW_LINE secuencia_sent NEW_LINE ENDPROCEDURE 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("def_proc",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // sent_while ::= WHILE expresion_compuesta NEW_LINE secuencia_sent NEW_LINE ENDWHILE 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_while",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // sent_do ::= DO NEW_LINE secuencia_sent NEW_LINE LOOP_UNTIL expresion_compuesta 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_do",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // sent_for ::= FOR ID ASSIGN expresion_simple TO expresion_simple STEP expresion_simple NEW_LINE secuencia_sent NEW_LINE NEXT ID 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_for",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-12)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // sent_for ::= FOR ID ASSIGN expresion_simple TO expresion_simple NEW_LINE secuencia_sent NEW_LINE NEXT ID 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_for",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // sent_if ::= IF expresion_compuesta THEN NEW_LINE secuencia_sent NEW_LINE ELSE NEW_LINE secuencia_sent NEW_LINE ENDIF 
            {
              Nodo RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).right;
		Nodo cond = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-9)).value;
		int verdaderoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int verdaderoright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		Nodo verdadero = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int falsoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int falsoright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo falso = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
											RESULT = new Condicion(((Comparacion) cond).getValor(),verdadero,falso);
									
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_if",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // sent_if ::= IF expresion_compuesta THEN NEW_LINE secuencia_sent NEW_LINE ENDIF 
            {
              Nodo RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Nodo cond = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int verdaderoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int verdaderoright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo verdadero = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
									RESULT = new Condicion(((Comparacion) cond).getValor(),verdadero);								
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_if",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // sent_leer ::= INPUT CADENA COMMA ID LPOPPER NUM_ENTERO RPOPPER 
            {
              Nodo RESULT =null;
		int cadleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int cadright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String cad = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int posleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int posright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer pos = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
									Nodo tmp = new Nodo(TIPO.sent_leer);
									tmp.add(new Constante(cad + "? "));
									tmp.add(new Identificador(id,pos+1));
									
									((Constante)tmp.getFirstChild()).imprimir();
									String lectura = buf.readLine();
									Object val;
									
									if(tabla_simbolos.getTipodatoAt(id)==DATO.STRING)
										val = lectura;
									else{
										if(tabla_simbolos.getTipodatoAt(id)==DATO.INTEGER)
											val = Integer.parseInt(lectura);
										else
											val = Float.parseFloat(lectura);
									}
									if(tabla_simbolos.setValor(id,val,pos))
										RESULT = tmp;
									else
										System.out.println("Error! - Variable no declarada / Tipos de datos incorrecto");
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_leer",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // sent_leer ::= INPUT CADENA COMMA ID 
            {
              Nodo RESULT =null;
		int cadleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cadright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String cad = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Nodo tmp = new Nodo(TIPO.sent_leer);
									tmp.add(new Constante(cad + "? "));
									tmp.add(new Identificador(id));
									
									((Constante)tmp.getFirstChild()).imprimir();
									String lectura = buf.readLine();
									Object val;
									
									if(tabla_simbolos.getTipodatoAt(id)==DATO.STRING)
										val = lectura;
									else{
										if(tabla_simbolos.getTipodatoAt(id)==DATO.INTEGER)
											val = Integer.parseInt(lectura);
										else
											val = Float.parseFloat(lectura);
									}
									if(tabla_simbolos.setValor(id,val))
										RESULT = tmp;
									else
										System.out.println("Error! - Variable no declarada / Tipos de datos incorrecto");
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_leer",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // sent_leer ::= INPUT ID LPOPPER NUM_ENTERO RPOPPER 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int posleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int posright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer pos = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
									Nodo tmp = new Nodo(TIPO.sent_leer);
									tmp.add(new Identificador(id,pos+1));
									
									String lectura = buf.readLine();
									Object val;
									
									if(tabla_simbolos.getTipodatoAt(id)==DATO.STRING)
										val = lectura;
									else{
										if(tabla_simbolos.getTipodatoAt(id)==DATO.INTEGER)
											val = Integer.parseInt(lectura);
										else
											val = Float.parseFloat(lectura);
									}
									if(tabla_simbolos.setValor(id,val,pos))
										RESULT = tmp;
									else
										System.out.println("Error! - Variable no declarada / Tipos de datos incorrecto");	
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_leer",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // sent_leer ::= INPUT ID 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Nodo tmp = new Nodo(TIPO.sent_leer);
									tmp.add(new Identificador(id));
									
									String lectura = buf.readLine();
									Object val;
									
									if(tabla_simbolos.getTipodatoAt(id)==DATO.STRING)
										val = lectura;
									else{
										if(tabla_simbolos.getTipodatoAt(id)==DATO.INTEGER)
											val = Integer.parseInt(lectura);
										else
											val = Float.parseFloat(lectura);
									}
									if(tabla_simbolos.setValor(id,val))
										RESULT = tmp;
									else
										System.out.println("Error! - Variable no declarada / Tipos de datos incorrecto");									
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_leer",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // list_impresion ::= expresion_simple 
            {
              Nodo RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo exp = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									if(exp.getTipo()==TIPO.CONSTANTE)
										((Constante)exp).imprimir();									
									else
										((Operacion)exp).imprimir();																		
									RESULT = exp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_impresion",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // list_impresion ::= list_impresion CONCAT expresion_simple 
            {
              Nodo RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo list = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int expleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo exp = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Nodo tmp = new Nodo(TIPO.list_impresion);
									tmp.add(list);
									tmp.add(exp);
									
									if(exp.getTipo()==TIPO.CONSTANTE)
										((Constante)exp).imprimir();									
									else
										((Operacion)exp).imprimir();	
									
									RESULT = tmp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_impresion",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // sent_escribir ::= PRINT list_impresion 
            {
              Nodo RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo list = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Nodo tmp = new Nodo(TIPO.sent_escribir);
									tmp.add(list);
									
									System.out.println();
									RESULT = tmp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_escribir",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // sent_asignacion ::= ID LPOPPER NUM_ENTERO RPOPPER ASSIGN expresion_simple 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int posleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int posright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Integer pos = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo list = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Asignacion tmp = new Asignacion(id,list,pos);
									
									if(tabla_simbolos.setValor(id,tmp.getValor(),pos))						
										RESULT = tmp;
									else
										System.out.println("Error! - Variable no declarada / Tipos de datos incorrecto");								
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_asignacion",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // sent_asignacion ::= ID ASSIGN expresion_simple 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo list = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Asignacion tmp = new Asignacion(id,list);
									
									if(tabla_simbolos.setValor(id,tmp.getValor()))						
										RESULT = tmp;
									else
										System.out.println("Error! - Variable no declarada / Tipos de datos incorrecto");
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_asignacion",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // list_var ::= ID 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
												
									RESULT = new Identificador(id);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_var",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // list_var ::= ID LPOPPER NUM_ENTERO RPOPPER 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int tamleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tamright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer tam = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
										
									if(tam==0)
										System.out.println("Error! - Vector declarado con tamaño 0");
									else
										RESULT = new Identificador(id,tam);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_var",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // list_var ::= list_var COMMA ID LPOPPER NUM_ENTERO RPOPPER 
            {
              Nodo RESULT =null;
		int listvarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int listvarright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Nodo listvar = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int tamleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tamright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer tam = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
									Nodo tmp = new Nodo(TIPO.list_var);									
									
									if(tam==0){									
										System.out.println("Error! - Vector declarado con tamaño 0");
									}else{
										tmp.add(listvar);
										tmp.add(new Identificador(id,tam));								
										RESULT = tmp;
									}
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_var",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // list_var ::= list_var COMMA ID 
            {
              Nodo RESULT =null;
		int listvarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int listvarright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo listvar = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Nodo tmp = new Nodo(TIPO.list_var);									
									tmp.add(listvar);
									tmp.add(new Identificador(id));
									
									RESULT = tmp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_var",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // tipo_dato ::= STRING 
            {
              DATO RESULT =null;
			RESULT = DATO.STRING; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // tipo_dato ::= FLOAT 
            {
              DATO RESULT =null;
			RESULT = DATO.FLOAT; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // tipo_dato ::= INTEGER 
            {
              DATO RESULT =null;
			RESULT = DATO.INTEGER; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // sent_declaracion ::= tipo_dato list_var 
            {
              Nodo RESULT =null;
		int datoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int datoright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		DATO dato = (DATO)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int listvarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listvarright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo listvar = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								/*-----------------------------------------------------------------------*/
								/*	Ingresando variables a la tabla de simbolos							*/
								/*-----------------------------------------------------------------------*/
								String namevar;/*	Nombre de la variable	*/
								int tam;/*	Tamaño del vector, -1 por defecto	*/
								
								/*	Si solo se declaro una variable listvar es un nodo IDENTIFICADOR	*/
								if(listvar.getTipo()==TIPO.IDENTIFICADOR){
									namevar = ((Identificador)listvar).getNamevar();
									tam = ((Identificador)listvar).getTam();
									/*	Si se declara un vector	*/
									if(((Identificador)listvar).isVector())
										tabla_simbolos.add(new Variable(dato,namevar,tam));
									else
										tabla_simbolos.add(new Variable(dato,namevar));										
								}else{
									/*	Si se declara mas de una variable en la linea se
										crea un nodo listvar	*/
									/*	Busco los nodos hojas (IDENTIFICADOR) a partir 
										del nodo listvar*/
									Identificador tmp = (Identificador)listvar.getFirstLeaf();									
									for(int i=0;i<listvar.getLeafCount();i++){
										namevar = tmp.getNamevar();
										tam = tmp.getTam();
										/*	Si se declara un vector	*/
										if(tmp.isVector())
											tabla_simbolos.add(new Variable(dato,namevar,tam));
										else
											tabla_simbolos.add(new Variable(dato,namevar));
											
										tmp = (Identificador)tmp.getNextLeaf();
									}
								}									
								/*-----------------------------------------------------------------------*/
								RESULT = new Declaracion(dato,listvar);
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_declaracion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sentencia ::= call_proc 
            {
              Nodo RESULT =null;
		int callprocleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int callprocright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo callproc = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									//RESULT = callproc;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sentencia ::= sent_while 
            {
              Nodo RESULT =null;
		int buclemientrasleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int buclemientrasright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo buclemientras = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									//RESULT = buclemientras;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // sentencia ::= sent_do 
            {
              Nodo RESULT =null;
		int buclehagaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int buclehagaright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo buclehaga = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									//RESULT = buclehaga;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // sentencia ::= sent_for 
            {
              Nodo RESULT =null;
		int bucleparaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int buclepararight = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo buclepara = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									//RESULT = buclepara;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // sentencia ::= sent_if 
            {
              Nodo RESULT =null;
		int decisionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int decisionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo decision = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = decision;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // sentencia ::= sent_leer 
            {
              Nodo RESULT =null;
		int leerleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int leerright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo leer = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = leer;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // sentencia ::= sent_escribir 
            {
              Nodo RESULT =null;
		int escribirleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int escribirright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo escribir = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = escribir;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // sentencia ::= sent_asignacion 
            {
              Nodo RESULT =null;
		int asignacionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int asignacionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo asignacion = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = asignacion;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // sentencia ::= sent_declaracion 
            {
              Nodo RESULT =null;
		int declaracionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int declaracionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo declaracion = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									RESULT = declaracion;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // secuencia_sent ::= sentencia 
            {
              Nodo RESULT =null;
		int sentleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sentright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo sent = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Nodo tmp = new Nodo(TIPO.secuencia_sent);									
									tmp.add(sent);
									RESULT = tmp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("secuencia_sent",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // secuencia_sent ::= secuencia_sent NEW_LINE sentencia 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sentleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sentright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo sent = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Nodo tmp = new Nodo(TIPO.secuencia_sent);
									tmp.add(secuencia);
									tmp.add(sent);

									RESULT = tmp;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("secuencia_sent",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // sub_programa ::= def_proc 
            {
              Nodo RESULT =null;
		int procleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int procright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo proc = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
										
									Nodo tmp = new Nodo(TIPO.sub_programa);
									tmp.add(proc);
									RESULT = tmp;									
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sub_programa",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sub_programa ::= sub_programa NEW_LINE def_proc 
            {
              Nodo RESULT =null;
		int subleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int subright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo sub = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int procleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int procright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo proc = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
									Nodo tmp = new Nodo(TIPO.sub_programa);
									tmp.add(sub);
									tmp.add(proc);
									
									RESULT = tmp;									
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sub_programa",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // programa ::= error 
            {
              Nodo RESULT =null;
			System.out.println("Error sintáctico!"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // programa ::= NEW_LINE END NEW_LINE sub_programa NEW_LINE 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // programa ::= NEW_LINE END NEW_LINE sub_programa 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // programa ::= END NEW_LINE sub_programa NEW_LINE 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // programa ::= END NEW_LINE sub_programa 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // programa ::= NEW_LINE END NEW_LINE 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // programa ::= END NEW_LINE 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // programa ::= END 
            {
              Nodo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // programa ::= NEW_LINE secuencia_sent NEW_LINE END NEW_LINE sub_programa NEW_LINE 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int subleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int subright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Nodo sub = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
			
									arbol.add(secuencia);
									arbol.add(sub);								
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // programa ::= NEW_LINE secuencia_sent NEW_LINE END NEW_LINE sub_programa 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int subleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int subright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo sub = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			
									arbol.add(secuencia);
									arbol.add(sub);								
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // programa ::= secuencia_sent NEW_LINE END NEW_LINE sub_programa NEW_LINE 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int subleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int subright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Nodo sub = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
									arbol.add(secuencia);
									arbol.add(sub);								
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // programa ::= secuencia_sent NEW_LINE END NEW_LINE sub_programa 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int subleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int subright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Nodo sub = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			
									arbol.add(secuencia);
									arbol.add(sub);								
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // programa ::= NEW_LINE secuencia_sent NEW_LINE END NEW_LINE 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		
									arbol.add(secuencia);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // programa ::= NEW_LINE secuencia_sent NEW_LINE END 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
									arbol.add(secuencia);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= secuencia_sent NEW_LINE END NEW_LINE 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		
									arbol.add(secuencia);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Nodo start_val = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // programa ::= secuencia_sent NEW_LINE END 
            {
              Nodo RESULT =null;
		int secuencialeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int secuenciaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Nodo secuencia = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
									arbol.add(secuencia);									
									arbol.printTree();									
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

