
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 03 00:17:07 VET 2011
//----------------------------------------------------

package sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RPOPPER = 40;
  public static final int LPOPPER = 39;
  public static final int CONCAT = 10;
  public static final int ASTERISK = 2;
  public static final int SLASH = 4;
  public static final int INPUT = 3;
  public static final int INTEGER = 29;
  public static final int LPAREN = 13;
  public static final int GREATER_THAN_EQ = 37;
  public static final int FOR = 25;
  public static final int MINUS = 17;
  public static final int GREATER_THAN = 36;
  public static final int LOOP_UNTIL = 18;
  public static final int RPAREN = 8;
  public static final int NOT = 34;
  public static final int AND = 32;
  public static final int ENDPROCEDURE = 45;
  public static final int LESS_THAN_EQ = 35;
  public static final int OR = 33;
  public static final int COMMA = 46;
  public static final int DIFFERENT = 42;
  public static final int NEXT = 28;
  public static final int PLUS = 7;
  public static final int ASSIGN = 19;
  public static final int IF = 12;
  public static final int ID = 15;
  public static final int ENDWHILE = 23;
  public static final int EOF = 0;
  public static final int EQUAL = 20;
  public static final int error = 1;
  public static final int CADENA = 48;
  public static final int NUM_FLOTANTE = 47;
  public static final int MODULE = 43;
  public static final int ENDIF = 21;
  public static final int ELSE = 6;
  public static final int NEW_LINE = 41;
  public static final int TO = 26;
  public static final int WHILE = 22;
  public static final int FLOAT = 30;
  public static final int THEN = 9;
  public static final int END = 11;
  public static final int NUM_ENTERO = 16;
  public static final int STRING = 31;
  public static final int CIRCUMFLEX = 38;
  public static final int LESS_THAN = 5;
  public static final int PROCEDURE = 44;
  public static final int PRINT = 14;
  public static final int DO = 24;
  public static final int STEP = 27;
}

